"use client";

import { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { mergeGeometries } from "three/examples/jsm/utils/BufferGeometryUtils.js";
import { RoundedBoxGeometry } from "three/examples/jsm/geometries/RoundedBoxGeometry.js";

export type SceneAsset = { id:string; label:string; category:string; details:string; meta:string; action?:"block-road"|"follow-vehicle"|"toggle-building-lights"; position?:{x:number;y:number;z:number} };

type Props = {
  running: boolean;
  blocked: boolean;
  blockedRoadId: number | null;
  showRisk: boolean;
  topView: boolean;
  nightMode: boolean;
  buildingLights: boolean;
  autoTour: boolean;
  suspended: boolean;
  scenarioPhase: number;
  scenarioTime: number;
  trafficDensity: number;
  onSelect: (asset: SceneAsset) => void;
  onRealRoute?: (route:{distance:number;eta:number;visited:number;roads:string[];blockedRoadId:number|null}) => void;
  onSceneStatus?: (status:"loading"|"ready"|"degraded") => void;
  plume: { lethal:number; high:number; warning:number; lethalWidth:number; highWidth:number; warningWidth:number };
};

function labelSprite(text: string, color: string) {
  const canvas = document.createElement("canvas");
  canvas.width = 420; canvas.height = 82;
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "rgba(4,15,22,.88)"; ctx.fillRect(0, 0, 420, 82);
  ctx.strokeStyle = color; ctx.lineWidth = 3; ctx.strokeRect(2, 2, 416, 78);
  ctx.fillStyle = "#e9fbff"; ctx.font = "600 29px Microsoft YaHei, sans-serif";
  ctx.fillText(text, 22, 52);
  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, transparent: true, depthTest: false }));
  sprite.scale.set(17, 3.3, 1);
  return sprite;
}

function landmark(scene: THREE.Scene, interactive: THREE.Object3D[], asset: SceneAsset, text: string, x: number, z: number, color: number) {
  const group = new THREE.Group(); group.position.set(x, 0, z); group.userData.asset = asset;
  const pole = new THREE.Mesh(new THREE.CylinderGeometry(.22, .28, 4.8, 12), new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: .25 }));
  pole.position.y = 2.4; pole.castShadow = true;
  const head = new THREE.Mesh(new THREE.SphereGeometry(.8, 18, 12), new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: .8 }));
  head.position.y = 5.2; head.userData.asset = asset;
  const halo = new THREE.Mesh(new THREE.RingGeometry(1.05, 1.3, 32), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .65, side: THREE.DoubleSide }));
  halo.rotation.x = -Math.PI / 2; halo.position.y = .15;
  const label = labelSprite(text, `#${color.toString(16).padStart(6,"0")}`); label.position.set(0, 7.1, 0);
  group.add(pole, head, halo, label); scene.add(group); interactive.push(head);
  return group;
}

function routeMesh(points: THREE.Vector3[], color: number) {
  const curve = new THREE.CatmullRomCurve3(points);
  const mesh = new THREE.Mesh(new THREE.TubeGeometry(curve, 48, .18, 8, false), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .92 }));
  mesh.position.y = .3;
  return mesh;
}

export default function CityScene({ running, blocked, blockedRoadId, showRisk, topView, nightMode, buildingLights, autoTour, suspended, scenarioPhase, scenarioTime, trafficDensity, onSelect, onRealRoute, onSceneStatus, plume }: Props) {
  const host = useRef<HTMLDivElement>(null);
  const runningRef = useRef(running); const onSelectRef = useRef(onSelect);const onRealRouteRef=useRef(onRealRoute);const onSceneStatusRef=useRef(onSceneStatus);
  const cameraRef = useRef<THREE.PerspectiveCamera | null>(null);
  const controlsRef = useRef<OrbitControls | null>(null);
  const riskRef = useRef<THREE.Mesh[]>([]); const routeARef = useRef<THREE.Mesh | null>(null);
  const riskBaseRef = useRef<Array<[number,number]>>([[1,1],[1,1],[1,1]]);
  const realRouteRef=useRef<Array<{x:number;z:number}>>([]);const blockedRef=useRef(blocked);const blockedRoadIdRef=useRef<number|null>(blockedRoadId);const realRoutePlannerRef=useRef<(blocked:boolean,roadId:number|null)=>void>(()=>{});
  const scenarioPhaseRef=useRef(scenarioPhase),scenarioTimeRef=useRef(scenarioTime),trafficDensityRef=useRef(trafficDensity);
  const tourRef = useRef(autoTour);const suspendedRef=useRef(suspended);const showRiskRef=useRef(showRisk);
  const nightRef = useRef(nightMode); const buildingLightsRef=useRef(buildingLights); const applyModeRef = useRef<(night:boolean)=>void>(()=>{});
  useEffect(()=>{runningRef.current=running},[running]); useEffect(()=>{onSelectRef.current=onSelect;onRealRouteRef.current=onRealRoute;onSceneStatusRef.current=onSceneStatus},[onSelect,onRealRoute,onSceneStatus]);
  useEffect(()=>{nightRef.current=nightMode;buildingLightsRef.current=buildingLights;applyModeRef.current(nightMode)},[nightMode,buildingLights]);
  useEffect(()=>{tourRef.current=autoTour},[autoTour]);
  useEffect(()=>{suspendedRef.current=suspended},[suspended]);
  useEffect(()=>{scenarioPhaseRef.current=scenarioPhase;scenarioTimeRef.current=scenarioTime},[scenarioPhase,scenarioTime]);
  useEffect(()=>{trafficDensityRef.current=trafficDensity},[trafficDensity]);
  useEffect(()=>{showRiskRef.current=showRisk;riskRef.current.forEach(x=>x.visible=showRisk)},[showRisk]);
  useEffect(()=>{blockedRef.current=blocked;blockedRoadIdRef.current=blockedRoadId;realRoutePlannerRef.current(blocked,blockedRoadId)},[blocked,blockedRoadId]);
  useEffect(()=>{const items=[[plume.warning,plume.warningWidth],[plume.high,plume.highWidth],[plume.lethal,plume.lethalWidth]];riskBaseRef.current=items.map(([length,width])=>[Math.max(1,length/80),Math.max(.8,width/80)]);riskRef.current.forEach((mesh,i)=>{mesh.position.x=-3+riskBaseRef.current[i][0];mesh.position.z=-3+riskBaseRef.current[i][0]*.42})},[plume]);
  useEffect(()=>{const c=cameraRef.current,o=controlsRef.current;if(!c||!o)return;if(topView){c.position.set(0,172,.1);o.target.set(0,0,0)}else{c.position.set(92,100,108);o.target.set(0,6,0)}o.update()},[topView]);

  useEffect(() => {
    onSceneStatusRef.current?.("loading");
    const el = host.current!; const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x8bc7e5); scene.fog = new THREE.FogExp2(0xb8d7df, .0038);
    const skyMaterial=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x68afe0)},horizon:{value:new THREE.Color(0xe2eef0)}},vertexShader:"varying vec3 vPos;void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}",fragmentShader:"uniform vec3 top;uniform vec3 horizon;varying vec3 vPos;void main(){float h=smoothstep(-.08,.55,normalize(vPos).y);gl_FragColor=vec4(mix(horizon,top,h),1.0);}"});const sky=new THREE.Mesh(new THREE.SphereGeometry(310,32,18),skyMaterial);scene.add(sky);
    const camera = new THREE.PerspectiveCamera(45, 1, .1, 700); camera.position.set(92,100,108); cameraRef.current = camera;
    const renderer = new THREE.WebGLRenderer({ antialias:true, alpha:false, powerPreference:"high-performance" });
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.4));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
    el.appendChild(renderer.domElement);const hoverTip=document.createElement("div");hoverTip.className="scene-hover-tip";el.appendChild(hoverTip);
    const controls = new OrbitControls(camera,renderer.domElement); controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=32;controls.maxDistance=220;controls.maxPolarAngle=Math.PI/2.08;controls.target.set(0,6,0);controlsRef.current=controls;
    const hemi=new THREE.HemisphereLight(0xbfeaff,0x52624e,2.8);scene.add(hemi);
    const sun = new THREE.DirectionalLight(0xfff1d2,3.1); sun.position.set(-35,65,28);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.bias=-.00025;sun.shadow.normalBias=.035;sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=75;sun.shadow.camera.bottom=-75;scene.add(sun);
    const environmentGroup=new THREE.Group();environmentGroup.name="北京城市远景";scene.add(environmentGroup);
    const distantGround=new THREE.Mesh(new THREE.CircleGeometry(385,96),new THREE.MeshStandardMaterial({color:0x0b1b20,roughness:.96,metalness:.02}));distantGround.rotation.x=-Math.PI/2;distantGround.position.y=-.7;environmentGroup.add(distantGround);
    const skylineCount=132,skylineGeo=new THREE.BoxGeometry(1,1,1),skylineMat=new THREE.MeshStandardMaterial({color:0x1b3038,roughness:.72,metalness:.2,emissive:0x0a2028,emissiveIntensity:.42});const skyline=new THREE.InstancedMesh(skylineGeo,skylineMat,skylineCount);const skylineMatrix=new THREE.Matrix4(),skylineQuat=new THREE.Quaternion(),skylineScale=new THREE.Vector3(),skylinePos=new THREE.Vector3();
    const skylineWindowMaterial=new THREE.MeshBasicMaterial({color:0xd7a65e,transparent:true,opacity:.08});const windowBands=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,.04),skylineWindowMaterial,skylineCount*3);let bandIndex=0;
    for(let i=0;i<skylineCount;i++){const angle=i*2.3999632297,radius=278+(i*17%35),width=3.4+(i*13%45)/10,depth=3.2+(i*7%24)/10,height=7+(i*29%250)/10;skylinePos.set(Math.cos(angle)*radius,height/2-.6,Math.sin(angle)*radius);skylineQuat.setFromAxisAngle(new THREE.Vector3(0,1,0),Math.PI/2-angle);skylineScale.set(width,height,depth);skylineMatrix.compose(skylinePos,skylineQuat,skylineScale);skyline.setMatrixAt(i,skylineMatrix);skyline.setColorAt(i,new THREE.Color(i%4===0?0x243b43:i%3===0?0x192e36:0x20343b));for(let row=1;row<=3;row++){skylinePos.set(Math.cos(angle)*(radius-depth*.51),height*(row/4)-.4,Math.sin(angle)*(radius-depth*.51));skylineScale.set(width*.72,.08,1);skylineMatrix.compose(skylinePos,skylineQuat,skylineScale);windowBands.setMatrixAt(bandIndex++,skylineMatrix)}}skyline.instanceMatrix.needsUpdate=true;windowBands.instanceMatrix.needsUpdate=true;environmentGroup.add(skyline,windowBands);
    const horizonGlow=new THREE.Mesh(new THREE.CylinderGeometry(265,325,38,96,1,true),new THREE.MeshBasicMaterial({color:0x37636b,transparent:true,opacity:.07,side:THREE.DoubleSide,depthWrite:false}));horizonGlow.position.y=14;environmentGroup.add(horizonGlow);
    const sunCanvas=document.createElement("canvas");sunCanvas.width=256;sunCanvas.height=256;const sunCtx=sunCanvas.getContext("2d")!;const sunGlow=sunCtx.createRadialGradient(128,128,8,128,128,122);sunGlow.addColorStop(0,"rgba(255,244,198,1)");sunGlow.addColorStop(.22,"rgba(255,185,94,.75)");sunGlow.addColorStop(1,"rgba(255,133,66,0)");sunCtx.fillStyle=sunGlow;sunCtx.fillRect(0,0,256,256);const sunTexture=new THREE.CanvasTexture(sunCanvas);const sunSprite=new THREE.Sprite(new THREE.SpriteMaterial({map:sunTexture,transparent:true,depthWrite:false,opacity:.72}));sunSprite.position.set(-155,82,-188);sunSprite.scale.set(38,38,1);environmentGroup.add(sunSprite);
    const moonCanvas=document.createElement("canvas");moonCanvas.width=256;moonCanvas.height=256;const moonCtx=moonCanvas.getContext("2d")!;const moonGlow=moonCtx.createRadialGradient(128,128,12,128,128,122);moonGlow.addColorStop(0,"rgba(235,247,255,1)");moonGlow.addColorStop(.2,"rgba(174,207,235,.72)");moonGlow.addColorStop(1,"rgba(103,158,211,0)");moonCtx.fillStyle=moonGlow;moonCtx.fillRect(0,0,256,256);const moonTexture=new THREE.CanvasTexture(moonCanvas);const moonSprite=new THREE.Sprite(new THREE.SpriteMaterial({map:moonTexture,transparent:true,depthWrite:false,opacity:.8}));moonSprite.position.set(150,96,-188);moonSprite.scale.set(30,30,1);moonSprite.visible=false;environmentGroup.add(moonSprite);
    const starPositions:number[]=[];for(let i=0;i<420;i++){const angle=i*2.3999632297,elevation=.14+((i*37)%80)/100*Math.PI*.36,radius=275;starPositions.push(Math.cos(angle)*Math.cos(elevation)*radius,Math.sin(elevation)*radius,Math.sin(angle)*Math.cos(elevation)*radius)}const starGeometry=new THREE.BufferGeometry();starGeometry.setAttribute("position",new THREE.Float32BufferAttribute(starPositions,3));const stars=new THREE.Points(starGeometry,new THREE.PointsMaterial({color:0xd8edff,size:.72,transparent:true,opacity:.76,depthWrite:false}));stars.visible=false;environmentGroup.add(stars);
    const mapTexture = new THREE.TextureLoader().load("./beijing-map-base.jpg"); mapTexture.colorSpace=THREE.SRGBColorSpace;mapTexture.anisotropy=renderer.capabilities.getMaxAnisotropy();mapTexture.wrapS=mapTexture.wrapT=THREE.ClampToEdgeWrapping;
    const groundMaterial=new THREE.MeshStandardMaterial({map:mapTexture,roughness:.92,metalness:.04,color:0xaebbb2});const ground = new THREE.Mesh(new THREE.PlaneGeometry(360,360),groundMaterial);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
    const grid = new THREE.GridHelper(360,72,0x4dd9e8,0x517077);grid.position.y=.035;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.045;scene.add(grid);

    type BeijingBuilding={id:number;points:Array<[number,number]>;height:number;heightMeters:number;levels:string|null;name:string;type:string;core:boolean};
    type BeijingRoad={id:number;points:Array<[number,number]>;width:number;name:string;type:string;core:boolean};
    const buildingGroup=new THREE.Group();buildingGroup.name="北京真实建筑群";scene.add(buildingGroup);
    const roadGroup=new THREE.Group();roadGroup.name="北京真实道路立体层";scene.add(roadGroup);
    const movingTraffic:Array<{mesh:THREE.Group;curve:THREE.CatmullRomCurve3;speed:number;travel:number;wheels:THREE.Mesh[];indicator:THREE.MeshBasicMaterial;asset:SceneAsset;position:THREE.Vector3;ahead:THREE.Vector3}>=[];
    const interactive:THREE.Object3D[]=[];
    const wallPalette=[0x415b63,0x617075,0x354e59,0x8b8274,0x49666d,0x5d6162];
    const residentialPalette=[0xb1aa9d,0x969990,0xc0b5a3,0x898f8d,0xa49a8b];
    const roofPalette=[0x607075,0x6b7878,0x52646a];
    const makeFacadeTexture=(variant:number)=>{
      const size=256,cellW=32,cellH=25.6,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d")!;
      const bases=["#18333d","#8d897f","#243f49","#9b9182","#314a54"],background=ctx.createLinearGradient(0,0,size,size);background.addColorStop(0,bases[variant%5]);background.addColorStop(.55,variant===1||variant===3?"#77746d":"#142b35");background.addColorStop(1,variant===4?"#52606a":bases[variant%5]);ctx.fillStyle=background;ctx.fillRect(0,0,size,size);
      for(let floor=0;floor<10;floor++)for(let bay=0;bay<8;bay++){
        const cellX=bay*cellW,cellY=floor*cellH,x=cellX+5,y=cellY+4,w=variant===2?20:22,h=variant===4?19:17;
        if(variant===1){ctx.fillStyle=floor%2?"#8f8b81":"#a19b90";ctx.fillRect(cellX+1,cellY+1,cellW-2,cellH-3);ctx.fillStyle="#30474e";ctx.fillRect(x+2,y+2,w-4,h-6);ctx.fillStyle="rgba(220,218,203,.7)";ctx.fillRect(cellX,y+18,cellW,3);ctx.fillStyle="rgba(61,67,65,.45)";ctx.fillRect(cellX,y+21,cellW,2)}
        else if(variant===3){ctx.fillStyle=(floor+bay)%2?"#8d8578":"#a19787";ctx.fillRect(cellX+1,cellY+1,cellW-2,cellH-2);ctx.fillStyle="#3a5259";ctx.fillRect(x+2,y+2,w-5,h-6);ctx.fillStyle="rgba(77,66,55,.28)";ctx.fillRect(cellX,cellY,2,cellH)}
        else{const glass=ctx.createLinearGradient(x,y,x+w,y+h);glass.addColorStop(0,variant===4?"#7e9da7":"#79b7c4");glass.addColorStop(.42,"#193b47");glass.addColorStop(.72,"#315e69");glass.addColorStop(1,"#9ac6cc");ctx.fillStyle=glass;ctx.fillRect(x,y,w,h);ctx.fillStyle="rgba(229,249,250,.28)";ctx.fillRect(x+2,y+2,2,h-4);ctx.fillStyle="rgba(9,30,38,.4)";ctx.fillRect(x+w-2,y+1,2,h-2);ctx.fillRect(x+1,y+h-2,w-2,2)}
        if((floor*13+bay*7+variant*5)%17<3){ctx.fillStyle=(floor+bay)%2?"rgba(255,214,139,.74)":"rgba(194,232,244,.56)";ctx.fillRect(x+4,y+3,Math.max(8,w-8),Math.max(7,h-8))}
      }
      ctx.strokeStyle=variant===1||variant===3?"rgba(63,61,56,.34)":"rgba(142,200,209,.4)";ctx.lineWidth=variant===2?2.5:1.2;for(let x=0;x<=size;x+=cellW){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,size);ctx.stroke()}for(let y=0;y<=size;y+=cellH){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(size,y);ctx.stroke()}
      if(variant!==1&&variant!==3){const reflection=ctx.createLinearGradient(0,0,size,0);reflection.addColorStop(.18,"rgba(255,255,255,0)");reflection.addColorStop(.42,"rgba(205,241,246,.14)");reflection.addColorStop(.55,"rgba(255,255,255,.27)");reflection.addColorStop(.7,"rgba(255,255,255,0)");ctx.save();ctx.translate(50,-30);ctx.rotate(.28);ctx.fillStyle=reflection;ctx.fillRect(0,0,170,330);ctx.restore()}
      for(let grain=0;grain<180;grain++){const x=(grain*73+variant*31)%size,y=(grain*47+variant*19)%size;ctx.fillStyle=grain%3?"rgba(255,255,255,.025)":"rgba(0,0,0,.035)";ctx.fillRect(x,y,1,1)}
      const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(.38,.74);texture.anisotropy=renderer.capabilities.getMaxAnisotropy();return texture;
    };
    const makeRoofTexture=()=>{const canvas=document.createElement("canvas");canvas.width=128;canvas.height=128;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#4a5a5e";ctx.fillRect(0,0,128,128);ctx.strokeStyle="rgba(163,194,197,.22)";ctx.lineWidth=2;for(let p=0;p<128;p+=16){ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,128);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(128,p);ctx.stroke()}ctx.fillStyle="rgba(17,40,46,.6)";ctx.fillRect(42,42,44,44);ctx.strokeStyle="rgba(194,220,221,.38)";ctx.strokeRect(45,45,38,38);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(.08,.08);texture.anisotropy=renderer.capabilities.getMaxAnisotropy();return texture};
    const makeEmissiveTexture=(variant:number)=>{const size=256,cellW=32,cellH=25.6,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#000";ctx.fillRect(0,0,size,size);for(let floor=0;floor<10;floor++)for(let bay=0;bay<8;bay++){const x=bay*cellW+5,y=floor*cellH+4,w=variant===2?20:22,h=variant===4?19:17,lit=(floor*13+bay*7+variant*5)%17;if(lit<7){ctx.fillStyle=lit%3===0?"#bfe9ff":lit%3===1?"#ffd58a":"#fff0c5";ctx.fillRect(x+4,y+3,Math.max(8,w-8),Math.max(7,h-8))}}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(.38,.74);texture.anisotropy=renderer.capabilities.getMaxAnisotropy();return texture};
    const facadeTextures=[0,1,2,3,4].map(makeFacadeTexture),emissiveTextures=[0,1,2,3,4].map(makeEmissiveTexture);const roofTexture=makeRoofTexture();
    const facadeMaterials:THREE.MeshStandardMaterial[]=[];const manualLitMaterials=new Set<THREE.MeshStandardMaterial>(),buildingGlowMaterials:THREE.MeshBasicMaterial[]=[],buildingNightLights:THREE.PointLight[]=[];const trafficLights:Array<{material:THREE.MeshBasicMaterial;day:number}>=[];let streetLampMaterial:THREE.MeshBasicMaterial|null=null;
    const applyMode=(night:boolean)=>{const cityLit=buildingLightsRef.current;scene.background=new THREE.Color(night?0x030916:0x8bc7e5);scene.fog=new THREE.FogExp2(night?0x07141d:0xb8d7df,night?.0045:.0038);skyMaterial.uniforms.top.value.set(night?0x030817:0x68afe0);skyMaterial.uniforms.horizon.value.set(night?0x102a3a:0xe2eef0);hemi.color.set(night?0x7294ba:0xbfeaff);hemi.groundColor.set(night?0x111b1a:0x52624e);hemi.intensity=night?1.15:2.8;sun.color.set(night?0x91aed2:0xfff1d2);sun.intensity=night?1.35:3.1;renderer.toneMappingExposure=night?.72:1.08;sunSprite.visible=!night;moonSprite.visible=night;stars.visible=night;skylineWindowMaterial.opacity=night&&cityLit?.68:.06;skylineWindowMaterial.needsUpdate=true;(horizonGlow.material as THREE.MeshBasicMaterial).color.set(night?0x1b4556:0xa5d2d8);(horizonGlow.material as THREE.MeshBasicMaterial).opacity=night?.07:.11;groundMaterial.color.set(night?0x8b9d99:0xaebbb2);skylineMat.color.set(night?0x1b3038:0x60747a);skylineMat.emissiveIntensity=night&&cityLit?.42:.06;facadeMaterials.forEach(m=>m.emissiveIntensity=manualLitMaterials.has(m)?1.28:cityLit?(night?.96:.08):.015);buildingGlowMaterials.forEach(m=>{m.opacity=night&&cityLit?.9:cityLit?.1:0;m.needsUpdate=true});buildingNightLights.forEach(light=>light.intensity=night&&cityLit?2.4:0);trafficLights.forEach(light=>{light.material.opacity=night?1:light.day;light.material.needsUpdate=true});if(streetLampMaterial)streetLampMaterial.opacity=night?1:.12};applyModeRef.current=applyMode;applyMode(nightRef.current);
    let chemicalRoutePath:Array<{x:number;z:number}>=[],ambulanceRoutePath:Array<{x:number;z:number}>=[],policeRoutePath:Array<{x:number;z:number}>=[];
    const chemicalRouteSeed=[new THREE.Vector3(-64.181,.4,-2.804),new THREE.Vector3(-34,.4,-5),new THREE.Vector3(-3,.4,-3)],ambulanceRouteSeed=[new THREE.Vector3(-32.836,.4,28.859),new THREE.Vector3(-20,.4,16),new THREE.Vector3(-3,.4,-3)],policeRouteSeed=[new THREE.Vector3(19.766,.4,-19.999),new THREE.Vector3(11,.4,-13),new THREE.Vector3(-3,.4,-3)],chemicalRouteLayer=routeMesh(chemicalRouteSeed,0xf0c84f),ambulanceRouteLayer=routeMesh(ambulanceRouteSeed,0x4ce3b1),policeRouteLayer=routeMesh(policeRouteSeed,0x4a91ff);chemicalRouteLayer.visible=false;ambulanceRouteLayer.visible=false;policeRouteLayer.visible=false;scene.add(chemicalRouteLayer,ambulanceRouteLayer,policeRouteLayer);
    const abortBuildings=new AbortController();let emergencyVehicle:THREE.Mesh|null=null,fireAssetData:SceneAsset|null=null;
    fetch("./beijing-buildings.json",{signal:abortBuildings.signal}).then(r=>{if(!r.ok)throw new Error(`地图数据响应异常：${r.status}`);return r.json()}).then((data:{buildings:BeijingBuilding[];roads:BeijingRoad[]})=>{if(!Array.isArray(data.buildings)||!Array.isArray(data.roads))throw new Error("地图数据结构异常");
      type RealEdge={to:string;cost:number;roadId:number;name:string};type SolvedRoute={path:Array<{x:number;z:number}>;edges:RealEdge[];distance:number;visited:number};
      const roadPositions=new Map<string,{x:number;z:number}>(),roadGraph=new Map<string,RealEdge[]>(),nodeKey=(x:number,z:number)=>`${x.toFixed(3)},${z.toFixed(3)}`,polylineCurve=(points:THREE.Vector3[])=>{const path=new THREE.CurvePath<THREE.Vector3>();for(let i=1;i<points.length;i++)path.add(new THREE.LineCurve3(points[i-1],points[i]));return path};
      data.roads.forEach(road=>{for(let i=0;i<road.points.length;i++){const [x,z]=road.points[i],key=nodeKey(x,z);roadPositions.set(key,{x,z});if(!roadGraph.has(key))roadGraph.set(key,[]);if(i===0)continue;const [px,pz]=road.points[i-1],previous=nodeKey(px,pz),cost=Math.hypot(x-px,z-pz);roadGraph.get(previous)!.push({to:key,cost,roadId:road.id,name:road.name});roadGraph.get(key)!.push({to:previous,cost,roadId:road.id,name:road.name})}});
      const nearestNode=(target:{x:number;z:number})=>{let best="",distance=Infinity;roadPositions.forEach((position,key)=>{const d=Math.hypot(position.x-target.x,position.z-target.z);if(d<distance){best=key;distance=d}});return best},startNode=nearestNode({x:-35,z:-30}),goalNode=nearestNode({x:-3,z:-3});
      const solveRealRoute=(excludedRoadId:number|null):SolvedRoute=>{const open=new Set<string>([startNode]),came=new Map<string,{from:string;edge:RealEdge}>(),g=new Map<string,number>([[startNode,0]]),f=new Map<string,number>([[startNode,Math.hypot(roadPositions.get(startNode)!.x-roadPositions.get(goalNode)!.x,roadPositions.get(startNode)!.z-roadPositions.get(goalNode)!.z)]]);let visited=0;while(open.size){let current="",best=Infinity;open.forEach(key=>{const score=f.get(key)??Infinity;if(score<best){best=score;current=key}});visited++;if(current===goalNode){const keys=[current],edges:RealEdge[]=[];while(came.has(current)){const step=came.get(current)!;edges.unshift(step.edge);current=step.from;keys.unshift(current)}return{path:keys.map(key=>roadPositions.get(key)!),edges,distance:g.get(goalNode)??0,visited}}open.delete(current);for(const edge of roadGraph.get(current)||[]){if(excludedRoadId!==null&&edge.roadId===excludedRoadId)continue;const tentative=(g.get(current)??Infinity)+edge.cost;if(tentative<(g.get(edge.to)??Infinity)){came.set(edge.to,{from:current,edge});g.set(edge.to,tentative);const next=roadPositions.get(edge.to)!,goal=roadPositions.get(goalNode)!;f.set(edge.to,tentative+Math.hypot(next.x-goal.x,next.z-goal.z));open.add(edge.to)}}}return{path:[],edges:[],distance:Infinity,visited}};
      const solveBetween=(routeStart:string,routeGoal:string,excludedRoadId:number|null):SolvedRoute=>{const open=new Set<string>([routeStart]),came=new Map<string,{from:string;edge:RealEdge}>(),g=new Map<string,number>([[routeStart,0]]),goalPosition=roadPositions.get(routeGoal)!;let visited=0;while(open.size){let current="",best=Infinity;open.forEach(key=>{const position=roadPositions.get(key)!,score=(g.get(key)??Infinity)+Math.hypot(position.x-goalPosition.x,position.z-goalPosition.z);if(score<best){best=score;current=key}});visited++;if(current===routeGoal){const keys=[current],edges:RealEdge[]=[];while(came.has(current)){const step=came.get(current)!;edges.unshift(step.edge);current=step.from;keys.unshift(current)}return{path:keys.map(key=>roadPositions.get(key)!),edges,distance:g.get(routeGoal)??0,visited}}open.delete(current);for(const edge of roadGraph.get(current)||[]){if(excludedRoadId!==null&&edge.roadId===excludedRoadId)continue;const tentative=(g.get(current)??Infinity)+edge.cost;if(tentative<(g.get(edge.to)??Infinity)){came.set(edge.to,{from:current,edge});g.set(edge.to,tentative);open.add(edge.to)}}}return{path:[],edges:[],distance:Infinity,visited}};
      const updateScenarioRoute=(mesh:THREE.Mesh,path:Array<{x:number;z:number}>)=>{if(path.length<2)return;mesh.geometry.dispose();const points=path.map(point=>new THREE.Vector3(point.x,.42,point.z));mesh.geometry=new THREE.TubeGeometry(polylineCurve(points),Math.min(360,Math.max(60,points.length*3)),.13,7,false)};
      const baseRoute=solveRealRoute(null),defaultBlockedEdge=baseRoute.edges.find((edge,index)=>index>baseRoute.edges.length*.45&&index<baseRoute.edges.length*.72&&edge.name==="东二环")||baseRoute.edges[Math.floor(baseRoute.edges.length*.58)],defaultBlockedRoadId=defaultBlockedEdge?.roadId??null;
      const chemicalSolved=solveBetween(nearestNode({x:-64.181,z:-2.804}),goalNode,null),ambulanceSolved=solveBetween(nearestNode({x:-32.836,z:28.859}),goalNode,null),policeSolved=solveBetween(nearestNode({x:19.766,z:-19.999}),goalNode,null);chemicalRoutePath=chemicalSolved.path;ambulanceRoutePath=ambulanceSolved.path;policeRoutePath=policeSolved.path;updateScenarioRoute(chemicalRouteLayer,chemicalRoutePath);updateScenarioRoute(ambulanceRouteLayer,ambulanceRoutePath);updateScenarioRoute(policeRouteLayer,policeRoutePath);
      const planRealRoute=(isBlocked:boolean,requestedRoadId:number|null)=>{const excludedRoadId=isBlocked?(requestedRoadId??defaultBlockedRoadId):null,alternative=isBlocked?solveRealRoute(excludedRoadId):baseRoute,result=alternative.path.length>1?alternative:baseRoute;realRouteRef.current=result.path;const points=result.path.map(p=>new THREE.Vector3(p.x,.4,p.z)),visibleRoute=routeARef.current;if(visibleRoute&&points.length>1){visibleRoute.geometry.dispose();visibleRoute.geometry=new THREE.TubeGeometry(polylineCurve(points),Math.min(420,Math.max(80,points.length*3)),.2,8,false);(visibleRoute.material as THREE.MeshBasicMaterial).color.set(isBlocked?0x53e7a8:0x28d9ef);visibleRoute.visible=true}const roads=[...new Set(result.edges.map(edge=>edge.name).filter(Boolean))],distance=Math.round(result.distance*15.2),first=result.path[0];if(first&&emergencyVehicle){emergencyVehicle.position.set(first.x,.65,first.z);if(fireAssetData?.position){fireAssetData.position.x=first.x;fireAssetData.position.z=first.z}}if(fireAssetData){fireAssetData.details=`正在沿 OSM 真实道路中心线行驶：${roads.slice(0,5).join(" → ")||"北京城市道路"}。`;fireAssetData.meta=`真实路网 A* · ${result.path.length} 个道路节点 · ${distance} 米${excludedRoadId?` · 已避开 OSM 道路 ${excludedRoadId}`:""}`}onRealRouteRef.current?.({distance,eta:Math.max(4,Math.ceil(distance/520)),visited:result.visited,roads:roads.slice(0,6),blockedRoadId:excludedRoadId})};realRoutePlannerRef.current=planRealRoute;planRealRoute(blockedRef.current,blockedRoadIdRef.current);
      const outerBuckets:Array<THREE.BufferGeometry[]>=[[],[],[]];
      const balconyMaterial=new THREE.MeshStandardMaterial({color:0xb8bfbc,metalness:.28,roughness:.5});
      const railingMaterial=new THREE.MeshStandardMaterial({color:0x405b62,metalness:.78,roughness:.22});
      const solarMaterial=new THREE.MeshStandardMaterial({color:0x183d52,metalness:.66,roughness:.22,emissive:0x0f3042,emissiveIntensity:.16});
      const hvacMaterial=new THREE.MeshStandardMaterial({color:0x849397,metalness:.5,roughness:.5});
      const entranceGlassMaterial=new THREE.MeshPhysicalMaterial({color:0x78b5c3,metalness:.48,roughness:.11,transmission:.12,transparent:true,opacity:.82,clearcoat:.72});
      const canopyMaterial=new THREE.MeshStandardMaterial({color:0xbec9c8,metalness:.76,roughness:.18});
      const bronzeAccentMaterial=new THREE.MeshStandardMaterial({color:0xa9804f,metalness:.82,roughness:.2});
      const stoneAccentMaterial=new THREE.MeshStandardMaterial({color:0xb7b0a3,metalness:.08,roughness:.62});
      const cornerGlassMaterial=new THREE.MeshPhysicalMaterial({color:0x6ea8b5,metalness:.5,roughness:.1,transparent:true,opacity:.76,clearcoat:.92,clearcoatRoughness:.08});
      const greenRoofMaterial=new THREE.MeshStandardMaterial({color:0x4f7357,roughness:.92,metalness:0});
      const planterMaterial=new THREE.MeshStandardMaterial({color:0x77716a,roughness:.72,metalness:.12});
      const foliageMaterial=new THREE.MeshStandardMaterial({color:0x547c5b,roughness:.88});
      const crownMaterial=new THREE.MeshStandardMaterial({color:0x58717a,metalness:.64,roughness:.24,emissive:0x183f49,emissiveIntensity:.3});
      const crownGlassMaterial=new THREE.MeshPhysicalMaterial({color:0x5c8f9b,metalness:.56,roughness:.12,transparent:true,opacity:.86,clearcoat:.88,emissive:0x214f5b,emissiveIntensity:.44});
      const parapetMaterial=new THREE.MeshStandardMaterial({color:0x718083,metalness:.42,roughness:.52});
      const entranceGlowMaterial=new THREE.MeshBasicMaterial({color:0xffd28a,transparent:true,opacity:nightRef.current&&buildingLightsRef.current?.9:.1}),rooflineGlowMaterial=new THREE.MeshBasicMaterial({color:0x8eeaff,transparent:true,opacity:nightRef.current&&buildingLightsRef.current?.82:.08});buildingGlowMaterials.push(entranceGlowMaterial,rooflineGlowMaterial);
      data.buildings.forEach((item,index)=>{
        if(item.points.length<3)return;
        const shape=new THREE.Shape();
        item.points.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();
        const detailedBevel=item.core&&item.height>2.4;const geometry=new THREE.ExtrudeGeometry(shape,{depth:item.height,bevelEnabled:detailedBevel,bevelSize:detailedBevel?.07:0,bevelThickness:detailedBevel?.07:0,bevelSegments:1});
        geometry.rotateX(-Math.PI/2);
        if(!item.core){outerBuckets[item.id%outerBuckets.length].push(geometry);return}
        const knownResidential=["apartments","residential","house","dormitory"].includes(item.type);const glassy=item.height>8||["office","commercial","retail","hotel"].includes(item.type);const residential=knownResidential||(!glassy&&item.height<7.5);const facadeIndex=residential?1:item.type==="hotel"?4:glassy?(item.id%2?0:2):3;const facade=facadeTextures[facadeIndex];
        const wallColor=residential?residentialPalette[item.id%residentialPalette.length]:wallPalette[item.id%wallPalette.length];const wall=new THREE.MeshPhysicalMaterial({color:wallColor,map:facade,bumpMap:facade,bumpScale:glassy?.045:.11,emissiveMap:emissiveTextures[facadeIndex],roughness:glassy?.24:.64,metalness:glassy?.5:.12,clearcoat:glassy?.48:.08,clearcoatRoughness:glassy?.2:.62,reflectivity:glassy?.82:.28,emissive:item.id%3===0?0xffd6a0:0xc8ecff,emissiveIntensity:buildingLightsRef.current?(nightRef.current?.96:.08):.015});facadeMaterials.push(wall);
        const roof=new THREE.MeshStandardMaterial({color:roofPalette[item.id%roofPalette.length],map:roofTexture,bumpMap:roofTexture,bumpScale:.06,roughness:.74,metalness:.16});
        const center=item.points.reduce((a,p)=>[a[0]+p[0]/item.points.length,a[1]+p[1]/item.points.length],[0,0]);const typeLabel:{[key:string]:string}={office:"写字楼",commercial:"商业建筑",retail:"商业综合体",hotel:"酒店",apartments:"住宅公寓",residential:"住宅",school:"教育建筑",hospital:"医疗建筑"};const asset:SceneAsset={id:`building-${item.id}`,label:item.name||`北京建筑 ${item.id}`,category:`真实建筑 · ${typeLabel[item.type]||"城市建筑"}`,details:`实际高度约 ${item.heightMeters.toFixed(1)} 米${item.levels?` · ${item.levels} 层`:""}。真实地图轮廓、高度与位置叠加精修幕墙、建筑收边及屋顶景观。`,meta:`OSM 建筑编号 ${item.id} · 精修立面 · 点击高亮 · 支持独立灯光控制`,action:"toggle-building-lights",position:{x:center[0],y:Math.max(2,item.height*.55),z:center[1]}};
        const mesh=new THREE.Mesh(geometry,[wall,roof]);mesh.name=asset.label;mesh.userData={asset,isBuilding:true};mesh.castShadow=item.height>4&&index%9===0;mesh.receiveShadow=true;buildingGroup.add(mesh);interactive.push(mesh);
        const xs=item.points.map(p=>p[0]),zs=item.points.map(p=>p[1]);const footprintW=Math.max(.45,Math.max(...xs)-Math.min(...xs)),footprintD=Math.max(.45,Math.max(...zs)-Math.min(...zs));
        if(item.height>2.6&&footprintW>.9&&index%6===0){const frontZ=center[1]+Math.min(footprintD*.53,3.8),doorW=Math.min(1.15,footprintW*.35),door=new THREE.Mesh(new THREE.BoxGeometry(doorW,.78,.055),entranceGlassMaterial);door.position.set(center[0],.42,frontZ);const canopy=new THREE.Mesh(new THREE.BoxGeometry(Math.min(1.65,footprintW*.5),.08,.58),canopyMaterial);canopy.position.set(center[0],.92,frontZ+.2);const entranceLight=new THREE.Mesh(new THREE.BoxGeometry(Math.min(1.25,doorW*1.2),.055,.06),entranceGlowMaterial);entranceLight.position.set(center[0],.86,frontZ+.49);const columns=[-.46,.46].map(side=>{const column=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,.9,8),canopyMaterial);column.position.set(center[0]+side*doorW,.45,frontZ+.4);return column});buildingGroup.add(door,canopy,entranceLight,...columns)}
        if(glassy&&item.height>7&&footprintW>2.2&&index%9===0){const frontZ=center[1]+Math.min(footprintD*.515,3.6),finH=Math.min(item.height*.72,8);for(let fin=-2;fin<=2;fin++){const shade=new THREE.Mesh(new THREE.BoxGeometry(.055,finH,.28),canopyMaterial);shade.position.set(center[0]+fin*Math.min(.48,footprintW*.12),finH/2+.8,frontZ+.12);buildingGroup.add(shade)}}
        if(glassy&&item.height>8&&footprintW>1.8&&index%15===0){const frontZ=center[1]+Math.min(footprintD*.52,3.7),accentH=Math.min(item.height*.82,11),offsetX=Math.min(footprintW*.36,2.1);[-1,1].forEach(side=>{const corner=new THREE.Mesh(new THREE.BoxGeometry(.14,accentH,.2),cornerGlassMaterial);corner.position.set(center[0]+side*offsetX,accentH/2+.45,frontZ+.09);const cap=new THREE.Mesh(new THREE.BoxGeometry(.22,.1,.27),bronzeAccentMaterial);cap.position.set(center[0]+side*offsetX,accentH+.48,frontZ+.09);buildingGroup.add(corner,cap)})}
        if(item.height>5.5&&footprintW>1.7&&footprintD>1.2&&index%16===0){const bandW=Math.min(footprintW*.88,6.2),bandD=Math.min(footprintD*.78,5.2),bands=Math.min(3,Math.max(2,Math.floor(item.height/4)));for(let level=1;level<=bands;level++){const y=item.height*level/(bands+1),front=new THREE.Mesh(new THREE.BoxGeometry(bandW,.08,.1),level%2?stoneAccentMaterial:bronzeAccentMaterial),back=front.clone(),east=new THREE.Mesh(new THREE.BoxGeometry(.1,.08,bandD),level%2?stoneAccentMaterial:bronzeAccentMaterial),west=east.clone();front.position.set(center[0],y,center[1]+bandD/2);back.position.set(center[0],y,center[1]-bandD/2);east.position.set(center[0]+bandW/2,y,center[1]);west.position.set(center[0]-bandW/2,y,center[1]);buildingGroup.add(front,back,east,west)}}
        if(residential&&item.height>2.8&&index%13===0){const floors=Math.min(6,Math.max(2,Math.round(item.height/1.15))),balconyW=Math.min(footprintW*.48,2.4),frontZ=center[1]+Math.min(footprintD*.53,3.7);for(let level=1;level<=floors;level++){const y=item.height*level/(floors+1),balcony=new THREE.Mesh(new THREE.BoxGeometry(balconyW,.06,.3),balconyMaterial);balcony.position.set(center[0],y,frontZ);const rail=new THREE.Mesh(new THREE.BoxGeometry(balconyW,.22,.025),railingMaterial);rail.position.set(center[0],y+.14,frontZ+.15);buildingGroup.add(balcony,rail)}}
        if(["commercial","retail","hotel","office"].includes(item.type)&&item.height>3.5&&footprintW>2&&index%12===0){const frontZ=center[1]+Math.min(footprintD*.54,3.9),awningW=Math.min(.72,footprintW*.18),spacing=Math.min(.9,footprintW*.22);[-1,0,1].forEach(slot=>{const awning=new THREE.Mesh(new THREE.BoxGeometry(awningW,.07,.5),slot===0?bronzeAccentMaterial:canopyMaterial);awning.rotation.x=-.08;awning.position.set(center[0]+slot*spacing,.78,frontZ+.22);const shopGlass=new THREE.Mesh(new THREE.BoxGeometry(awningW*.82,.58,.045),entranceGlassMaterial);shopGlass.position.set(center[0]+slot*spacing,.38,frontZ+.03);buildingGroup.add(awning,shopGlass)})}
        if(item.height>7&&index%5===0){
          const podiumH=Math.min(1.05,item.height*.1),podium=new THREE.Mesh(new THREE.BoxGeometry(Math.min(footprintW*1.08,7.5),podiumH,Math.min(footprintD*1.08,7.5)),new THREE.MeshStandardMaterial({color:0x35484d,metalness:.3,roughness:.48,emissive:0x18353d,emissiveIntensity:.28}));podium.position.set(center[0],podiumH/2,center[1]);podium.castShadow=true;podium.receiveShadow=true;buildingGroup.add(podium);
          const lobby=new THREE.Mesh(new THREE.BoxGeometry(Math.min(footprintW*.55,3.2),.14,.08),entranceGlowMaterial);lobby.position.set(center[0],.42,center[1]+Math.min(footprintD*.54,3.8));buildingGroup.add(lobby);
        }
        if(item.height>3.2&&index%3===0){
          const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry,24),new THREE.LineBasicMaterial({color:0x74a6b0,transparent:true,opacity:.2}));buildingGroup.add(edges);
        }
        if(item.height>6.5&&index%4===0){
          const rooftop=new THREE.Mesh(new THREE.BoxGeometry(.95,.75,.95),new THREE.MeshStandardMaterial({color:0x66777b,metalness:.55,roughness:.45}));rooftop.position.set(center[0],item.height+.38,center[1]);buildingGroup.add(rooftop);
          const antennaHeight=Math.min(2.2,item.height*.12);const antenna=new THREE.Mesh(new THREE.CylinderGeometry(.025,.045,antennaHeight,6),new THREE.MeshStandardMaterial({color:0xbadbe0,emissive:0x5dd9e8,emissiveIntensity:.35}));antenna.position.set(center[0],item.height+.75+antennaHeight/2,center[1]);buildingGroup.add(antenna);
          if(item.height>12){const beacon=new THREE.Mesh(new THREE.SphereGeometry(.075,10,8),new THREE.MeshBasicMaterial({color:0xff493d}));beacon.position.set(center[0],item.height+.8+antennaHeight,center[1]);buildingGroup.add(beacon)}
        }
        if(item.height>2.2&&index%7===0){
          const hvac=new THREE.Mesh(new THREE.BoxGeometry(1.3,.42,.75),hvacMaterial);hvac.position.set(center[0]+.65,item.height+.22,center[1]-.35);const fan=new THREE.Mesh(new THREE.TorusGeometry(.17,.025,6,14),railingMaterial);fan.rotation.x=Math.PI/2;fan.position.set(center[0]+.65,item.height+.45,center[1]-.35);buildingGroup.add(hvac,fan);
        }
        if(item.height>4&&index%11===0){const panel=new THREE.Mesh(new THREE.BoxGeometry(Math.min(1.6,footprintW*.42),.06,.78),solarMaterial);panel.rotation.x=-.13;panel.position.set(center[0]-.5,item.height+.16,center[1]+.25);buildingGroup.add(panel)}
        if(item.height>5&&footprintW>1.8&&footprintD>1.6&&index%23===0){const gardenW=Math.min(footprintW*.58,3.4),gardenD=Math.min(footprintD*.54,2.8),garden=new THREE.Mesh(new THREE.BoxGeometry(gardenW,.08,gardenD),greenRoofMaterial);garden.position.set(center[0],item.height+.13,center[1]);buildingGroup.add(garden);[-.32,0,.32].forEach((offset,treeIndex)=>{const planter=new THREE.Mesh(new THREE.CylinderGeometry(.16,.2,.18,8),planterMaterial);planter.position.set(center[0]+offset*gardenW,item.height+.25,center[1]+(treeIndex%2?.2:-.16)*gardenD);const foliage=new THREE.Mesh(new THREE.IcosahedronGeometry(.25+treeIndex*.035,1),foliageMaterial);foliage.position.set(planter.position.x,item.height+.56,planter.position.z);buildingGroup.add(planter,foliage)})}
        if(item.height>11&&footprintW>2.4&&footprintD>2&&index%18===0){const terraceW=Math.min(footprintW*.62,4.5),terraceD=Math.min(footprintD*.58,3.8),terrace=new THREE.Mesh(new THREE.BoxGeometry(terraceW,.13,terraceD),stoneAccentMaterial);terrace.position.set(center[0],item.height+.1,center[1]);const pergolaTop=new THREE.Mesh(new THREE.BoxGeometry(terraceW*.62,.08,terraceD*.32),bronzeAccentMaterial);pergolaTop.position.set(center[0],item.height+.78,center[1]);const posts=[[-1,-1],[-1,1],[1,-1],[1,1]].map(([sx,sz])=>{const post=new THREE.Mesh(new THREE.BoxGeometry(.055,.65,.055),bronzeAccentMaterial);post.position.set(center[0]+sx*terraceW*.29,item.height+.44,center[1]+sz*terraceD*.13);return post});buildingGroup.add(terrace,pergolaTop,...posts)}
        if(item.height>5&&index%17===0){const waterTank=new THREE.Mesh(new THREE.CylinderGeometry(.34,.38,.52,16),new THREE.MeshStandardMaterial({color:0x8a999b,metalness:.7,roughness:.34}));waterTank.position.set(center[0]-.5,item.height+.28,center[1]-.35);const dish=new THREE.Mesh(new THREE.SphereGeometry(.32,14,8,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0xc2cbcb,metalness:.72,roughness:.25,side:THREE.DoubleSide}));dish.rotation.z=-.55;dish.position.set(center[0]+.45,item.height+.42,center[1]+.25);buildingGroup.add(waterTank,dish)}
        if(item.height>8&&index%14===0){const edgeW=Math.min(footprintW*.7,4),edgeD=Math.min(footprintD*.7,4),roofZ=center[1]+edgeD*.5;const roofline=new THREE.Mesh(new THREE.BoxGeometry(edgeW,.045,.045),rooflineGlowMaterial);roofline.position.set(center[0],item.height+.18,roofZ);buildingGroup.add(roofline)}
        if(item.height>6&&buildingNightLights.length<12&&index%37===0){const frontZ=center[1]+Math.min(footprintD*.57,4.1),light=new THREE.PointLight(index%2?0xffc879:0xb8e9ff,nightRef.current&&buildingLightsRef.current?2.4:0,10,2);light.position.set(center[0],1.25,frontZ);buildingNightLights.push(light);scene.add(light)}
        if(item.height>4&&index%19===0){const parapetH=.22,parapetW=Math.min(footprintW*.72,4.2),parapetD=Math.min(footprintD*.72,4.2),north=new THREE.Mesh(new THREE.BoxGeometry(parapetW,parapetH,.08),parapetMaterial),south=north.clone(),east=new THREE.Mesh(new THREE.BoxGeometry(.08,parapetH,parapetD),parapetMaterial),west=east.clone();north.position.set(center[0],item.height+parapetH/2,center[1]+parapetD/2);south.position.set(center[0],item.height+parapetH/2,center[1]-parapetD/2);east.position.set(center[0]+parapetW/2,item.height+parapetH/2,center[1]);west.position.set(center[0]-parapetW/2,item.height+parapetH/2,center[1]);buildingGroup.add(north,south,east,west)}
        if(item.height>12&&index%3===0){const crownW=Math.min(footprintW*.5,2.8),crownD=Math.min(footprintD*.5,2.8),crownType=item.id%3;if(crownType===0){const lower=new THREE.Mesh(new THREE.BoxGeometry(crownW,.46,crownD),crownMaterial),upper=new THREE.Mesh(new THREE.BoxGeometry(crownW*.68,.5,crownD*.68),crownGlassMaterial);lower.position.set(center[0],item.height+.23,center[1]);upper.position.set(center[0],item.height+.71,center[1]);buildingGroup.add(lower,upper)}else if(crownType===1){const drum=new THREE.Mesh(new THREE.CylinderGeometry(crownW*.34,crownW*.46,.7,12),crownGlassMaterial),spire=new THREE.Mesh(new THREE.ConeGeometry(crownW*.16,.75,8),bronzeAccentMaterial);drum.position.set(center[0],item.height+.35,center[1]);spire.position.set(center[0],item.height+1.05,center[1]);buildingGroup.add(drum,spire)}else{const crown=new THREE.Mesh(new THREE.ConeGeometry(crownW*.48,1.05,4),crownMaterial),cap=new THREE.Mesh(new THREE.SphereGeometry(.09,10,8),rooflineGlowMaterial);crown.rotation.y=Math.PI/4;crown.position.set(center[0],item.height+.52,center[1]);cap.position.set(center[0],item.height+1.08,center[1]);buildingGroup.add(crown,cap)}}
      });
      outerBuckets.forEach((bucket,bucketIndex)=>{const material=new THREE.MeshStandardMaterial({color:wallPalette[(bucketIndex+1)%wallPalette.length],map:facadeTextures[bucketIndex],bumpMap:facadeTextures[bucketIndex],bumpScale:.045,roughness:.46,metalness:.25,emissiveMap:emissiveTextures[bucketIndex],emissive:bucketIndex%2?0xffd6a0:0xc8ecff,emissiveIntensity:buildingLightsRef.current?(nightRef.current?.72:.06):.012});facadeMaterials.push(material);for(let start=0;start<bucket.length;start+=650){const source=bucket.slice(start,start+650),merged=mergeGeometries(source,false);source.forEach(g=>g.dispose());if(merged){const mesh=new THREE.Mesh(merged,material);mesh.receiveShadow=true;buildingGroup.add(mesh)}}});
      const roadMaterials:Record<string,THREE.MeshStandardMaterial>={trunk:new THREE.MeshStandardMaterial({color:0xb98258,roughness:.7,metalness:.06,emissive:0x3a1a0a,emissiveIntensity:.16}),trunk_link:new THREE.MeshStandardMaterial({color:0x9c7659,roughness:.74}),secondary:new THREE.MeshStandardMaterial({color:0x6e8589,roughness:.78}),secondary_link:new THREE.MeshStandardMaterial({color:0x5c7479,roughness:.8})};
      const roadGeometryBuckets:Record<string,THREE.BufferGeometry[]>={trunk:[],trunk_link:[],secondary:[],secondary_link:[]};
      const lampPositions:Array<THREE.Vector3>=[];
      (data.roads||[]).forEach((road,index)=>{
        if(road.points.length<2)return;const points=road.points.map(([x,z])=>new THREE.Vector3(x,.13,z));
        const curve=new THREE.CatmullRomCurve3(points,false,"centripetal");roadGeometryBuckets[road.type]?.push(new THREE.TubeGeometry(curve,Math.min(42,Math.max(6,points.length*3)),road.width,6,false));
        if(road.core&&road.name){const midpoint=curve.getPointAt(.5),roadHitMaterial=new THREE.MeshBasicMaterial({color:0xff4d45,transparent:true,opacity:.025,depthWrite:false});const roadHit=new THREE.Mesh(new THREE.TubeGeometry(curve,Math.min(42,Math.max(6,points.length*3)),Math.max(.38,road.width*2.2),6,false),roadHitMaterial);roadHit.userData={isRoad:true,asset:{id:`road-${road.id}`,label:road.name,category:"真实道路 · 可交互封锁",details:`道路类型：${road.type.includes("trunk")?"城市快速路":"城市主干路"}。点击下方按钮可模拟封锁此道路，并触发应急车辆路径重规划。`,meta:`OSM 道路编号 ${road.id} · 实时交通状态：通行`,action:"block-road",position:{x:midpoint.x,y:1.2,z:midpoint.z}} satisfies SceneAsset};roadGroup.add(roadHit);interactive.push(roadHit)}
        if((road.type==="trunk"||road.type==="secondary")&&index%2===0){for(let i=1;i<points.length-1&&lampPositions.length<84;i+=2)lampPositions.push(points[i])}
        if(points.length>2&&index%3===0&&movingTraffic.length<54){
          const car=new THREE.Group(),fleetIndex=movingTraffic.length,modelIndex=fleetIndex%7,isTaxi=modelIndex===1,isSuv=modelIndex===2,isVan=modelIndex===3,isBus=modelIndex===4,isEv=modelIndex===5,isCoupe=modelIndex===6,vehicleLabel=isTaxi?"北京巡游出租车":isSuv?"城市 SUV":isVan?"城市配送车":isBus?"城市公交小巴":isEv?"新能源掀背车":isCoupe?"运动轿跑":"城市轿车",color=isTaxi?0xd5b72f:isBus?0x3d87c9:isEv?0x65b8a0:[0xd84d43,0xe6e8e4,0x3b8dc4,0x242a31,0xa8653c][fleetIndex%5],bodyH=isBus?.42:isVan?.35:isSuv?.3:isCoupe?.2:.24,bodyL=isBus?1.22:isVan?.96:isSuv?.84:isCoupe?.86:.78,bodyW=isBus?.46:isSuv?.42:.38;
          const asset:SceneAsset={id:`traffic-${fleetIndex+1}`,label:`${vehicleLabel} ${String(fleetIndex+1).padStart(2,"0")}`,category:"实时交通 · 可跟随车辆",details:`车牌 京A·${String(7318+fleetIndex*137).slice(-4)} · 当前速度 ${36+fleetIndex%7*4} km/h · 沿北京真实道路行驶。`,meta:"实时轨迹更新 · 点击下方按钮进入车辆跟随视角",action:"follow-vehicle",position:{x:points[0].x,y:1.2,z:points[0].z}};
          const body=new THREE.Mesh(new RoundedBoxGeometry(bodyW,bodyH,bodyL,3,.055),new THREE.MeshPhysicalMaterial({color,metalness:isBus?.38:.58,roughness:isBus?.34:.26,clearcoat:.72,clearcoatRoughness:.2}));body.position.y=.25;body.castShadow=fleetIndex<12;body.userData={asset,isVehicle:true,modelQuality:"competition-realism-v2"};interactive.push(body);
          const cabin=new THREE.Mesh(new RoundedBoxGeometry(bodyW*.86,isBus?.38:isVan?.34:isSuv?.26:.2,isBus?.78:isVan?.54:isCoupe?.36:.4,3,.045),new THREE.MeshPhysicalMaterial({color:isEv?0x9bd1d1:0x8eb8c1,metalness:.72,roughness:.13,clearcoat:.9,transparent:true,opacity:.88}));cabin.position.set(0,.43+((isVan||isBus)?0.08:0),isBus?.08:isVan?.08:.03);
          const headMat=new THREE.MeshBasicMaterial({color:0xffefb0,transparent:true,opacity:nightRef.current?1:.28}),tailMat=new THREE.MeshBasicMaterial({color:0xff3028,transparent:true,opacity:nightRef.current?1:.56}),indicator=new THREE.MeshBasicMaterial({color:0xffa51f,transparent:true,opacity:.18});trafficLights.push({material:headMat,day:.28},{material:tailMat,day:.56});const headlights=new THREE.Mesh(new THREE.BoxGeometry(.25,.065,.04),headMat);headlights.position.set(0,.28,-bodyL*.52);const tailLights=new THREE.Mesh(new THREE.BoxGeometry(.25,.06,.035),tailMat);tailLights.position.set(0,.28,bodyL*.52);const turnLeft=new THREE.Mesh(new THREE.BoxGeometry(.065,.055,.045),indicator),turnRight=turnLeft.clone();turnLeft.position.set(-.145,.29,-bodyL*.53);turnRight.position.set(.145,.29,-bodyL*.53);
          const wheels:THREE.Mesh[]=[];const wheelGeo=new THREE.CylinderGeometry(isBus?.105:.09,isBus?.105:.09,.075,12),wheelMat=new THREE.MeshStandardMaterial({color:0x111519,roughness:.88}),hubMat=new THREE.MeshStandardMaterial({color:0x9da7aa,metalness:.8,roughness:.25});[[-bodyW*.54,-bodyL*.3],[bodyW*.54,-bodyL*.3],[-bodyW*.54,bodyL*.3],[bodyW*.54,bodyL*.3]].forEach(([x,z])=>{const wheel=new THREE.Mesh(wheelGeo,wheelMat);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.16,z);wheels.push(wheel);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.08,10),hubMat);hub.rotation.z=Math.PI/2;hub.position.copy(wheel.position);car.add(wheel,hub)});const frontPlate=new THREE.Mesh(new THREE.BoxGeometry(.13,.04,.012),new THREE.MeshBasicMaterial({color:0x2b69ae}));frontPlate.position.set(0,.19,-bodyL*.55);const mirrorMat=new THREE.MeshStandardMaterial({color:0x232c30,metalness:.55,roughness:.35}),leftMirror=new THREE.Mesh(new THREE.BoxGeometry(.08,.045,.08),mirrorMat),rightMirror=leftMirror.clone();leftMirror.position.set(-bodyW*.62,.42,-.1);rightMirror.position.set(bodyW*.62,.42,-.1);car.add(body,cabin,headlights,tailLights,turnLeft,turnRight,frontPlate,leftMirror,rightMirror);if(isTaxi){const taxiSign=new THREE.Mesh(new THREE.BoxGeometry(.17,.08,.1),new THREE.MeshBasicMaterial({color:0xfff0a1}));taxiSign.position.set(0,.59,.04);car.add(taxiSign)}if(isBus){[-.28,.05,.34].forEach(z=>{const leftWindow=new THREE.Mesh(new THREE.BoxGeometry(.02,.18,.2),new THREE.MeshBasicMaterial({color:0x8fd4e0})),rightWindow=leftWindow.clone();leftWindow.position.set(-bodyW*.51,.52,z);rightWindow.position.set(bodyW*.51,.52,z);car.add(leftWindow,rightWindow)})}if(isEv){const evRoof=new THREE.Mesh(new THREE.BoxGeometry(.2,.035,.24),new THREE.MeshBasicMaterial({color:0x65f0d2}));evRoof.position.set(0,.57,.02);car.add(evRoof)}if(isCoupe){const spoiler=new THREE.Mesh(new THREE.BoxGeometry(.36,.035,.08),mirrorMat);spoiler.position.set(0,.43,bodyL*.43);car.add(spoiler)}roadGroup.add(car);movingTraffic.push({mesh:car,curve,speed:(isBus?.019:.025)+(fleetIndex%5)*.004,travel:(fleetIndex*.137)%2,wheels,indicator,asset,position:new THREE.Vector3(),ahead:new THREE.Vector3()});
        }
      });
      Object.entries(roadGeometryBuckets).forEach(([kind,bucket])=>{for(let start=0;start<bucket.length;start+=250){const source=bucket.slice(start,start+250),merged=mergeGeometries(source,false);source.forEach(g=>g.dispose());if(merged){const mesh=new THREE.Mesh(merged,roadMaterials[kind]||roadMaterials.secondary);mesh.receiveShadow=true;roadGroup.add(mesh)}}});
      if(lampPositions.length){
        const poleGeo=new THREE.CylinderGeometry(.025,.035,.9,6),poleMat=new THREE.MeshStandardMaterial({color:0x5c7175,metalness:.65,roughness:.42});const poles=new THREE.InstancedMesh(poleGeo,poleMat,lampPositions.length);
        const lampGeo=new THREE.SphereGeometry(.07,8,6),lampMat=new THREE.MeshBasicMaterial({color:0xffd98a,transparent:true,opacity:nightRef.current?1:.12});streetLampMaterial=lampMat;const lamps=new THREE.InstancedMesh(lampGeo,lampMat,lampPositions.length);const matrix=new THREE.Matrix4();
        lampPositions.forEach((p,i)=>{matrix.makeTranslation(p.x,.57,p.z);poles.setMatrixAt(i,matrix);matrix.makeTranslation(p.x,1.04,p.z);lamps.setMatrixAt(i,matrix)});poles.instanceMatrix.needsUpdate=true;lamps.instanceMatrix.needsUpdate=true;roadGroup.add(poles,lamps);
      }
      onSceneStatusRef.current?.("ready");
    }).catch(error=>{if(error?.name!=="AbortError"){console.warn("北京建筑数据载入失败",error);onSceneStatusRef.current?.("degraded")}});
    for(let i=0;i<36;i++){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.5,6),new THREE.MeshStandardMaterial({color:0x4b3424}));const crown=new THREE.Mesh(new THREE.ConeGeometry(.8,2.2,8),new THREE.MeshStandardMaterial({color:0x236044}));const x=29+(i%9)*3.1,z=22+Math.floor(i/9)*4;trunk.position.set(x,.75,z);crown.position.set(x,2.1,z);scene.add(trunk,crown)}
    const incidentLandmark=landmark(scene,interactive,{id:"incident",label:"危化品泄漏源",category:"重大事故 · 实时监测",details:"罐体尾阀受损 · 下风向浓度持续上升，风险扩散模型正在实时推演。",meta:"事件由完整演示状态机实时驱动"},"危化品泄漏源",-3,-3,0xff5149);incidentLandmark.visible=false;landmark(scene,interactive,{id:"school",label:"城北实验学校",category:"重点保护目标",details:"在校师生 2,146 人 · 东南侧上风向安全通道畅通。",meta:"距事故点 480m · 预防性疏散状态实时更新"},"城北实验学校",35,-23,0x43def1);landmark(scene,interactive,{id:"hospital",label:"市第三人民医院",category:"医疗救援资源",details:"急诊绿色通道已启用 · 医疗队 3 组待命。",meta:"三级医院 · 救治能力充足"},"市第三人民医院",-37,28,0x42dda2);landmark(scene,interactive,{id:"station",label:"青岚消防站",category:"消防救援资源",details:"2 辆泡沫消防车、1 辆洗消车已出动。",meta:"应急响应中 · 路径由 A* 算法规划"},"青岚消防站",-35,-30,0xffa34d);
    const routeA=routeMesh([new THREE.Vector3(-35,.4,-30),new THREE.Vector3(-20,.4,-18),new THREE.Vector3(-3,.4,-3)],0x28d9ef);routeA.visible=false;scene.add(routeA);routeARef.current=routeA;
    const riskMeshes:THREE.Mesh[]=[];[[1,0xf6cf4a,.18],[1,0xff8f3d,.23],[1,0xff4545,.3]].forEach(([r,c,o])=>{const m=new THREE.Mesh(new THREE.CircleGeometry(r as number,64),new THREE.MeshBasicMaterial({color:c as number,transparent:true,opacity:o as number,depthWrite:false,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(-3,.18,-3);m.visible=showRiskRef.current;scene.add(m);riskMeshes.push(m)});riskRef.current=riskMeshes;
    const vehicleMat=new THREE.MeshPhysicalMaterial({color:0xcc382f,metalness:.42,roughness:.28,clearcoat:.78,clearcoatRoughness:.18,emissive:0x54150f,emissiveIntensity:.24});const vehicle=new THREE.Mesh(new RoundedBoxGeometry(1.25,.46,2.4,4,.12),vehicleMat);const fireCab=new THREE.Mesh(new RoundedBoxGeometry(1.08,.92,.76,4,.12),new THREE.MeshPhysicalMaterial({color:0xe94c38,metalness:.38,roughness:.27,clearcoat:.82,clearcoatRoughness:.16}));fireCab.position.set(0,.45,-.7);const fireGlass=new THREE.Mesh(new RoundedBoxGeometry(.78,.35,.035,3,.04),new THREE.MeshPhysicalMaterial({color:0x7fb3c3,metalness:.72,roughness:.1,clearcoat:1,transparent:true,opacity:.9}));fireGlass.position.set(0,.54,-1.095);const fireTank=new THREE.Mesh(new RoundedBoxGeometry(1.04,.76,1.12,3,.08),new THREE.MeshStandardMaterial({color:0xcfd8d7,metalness:.66,roughness:.3}));fireTank.position.set(0,.38,.42);const cannonBase=new THREE.Mesh(new THREE.CylinderGeometry(.18,.22,.12,12),new THREE.MeshStandardMaterial({color:0x8b999b,metalness:.7,roughness:.3}));cannonBase.position.set(0,.85,.42);const cannon=new THREE.Mesh(new THREE.CylinderGeometry(.055,.07,.72,10),new THREE.MeshStandardMaterial({color:0xc4d0d1,metalness:.8,roughness:.22}));cannon.rotation.x=Math.PI/2;cannon.position.set(0,1.02,.18);const fireBeacon=new THREE.Mesh(new RoundedBoxGeometry(.7,.12,.2,2,.035),new THREE.MeshBasicMaterial({color:0x3aaeff}));fireBeacon.position.set(0,.98,-.7);const fireLightMat=new THREE.MeshBasicMaterial({color:0xfff0ba}),fireHeadlights=new THREE.Mesh(new RoundedBoxGeometry(.62,.12,.035,2,.025),fireLightMat);fireHeadlights.position.set(0,.05,-1.22);const lockerMat=new THREE.MeshStandardMaterial({color:0xbec9c9,metalness:.72,roughness:.3});[-.631,.631].forEach(x=>{for(let z=-.05;z<=.72;z+=.38){const locker=new THREE.Mesh(new RoundedBoxGeometry(.025,.52,.32,2,.02),lockerMat);locker.position.set(x,.32,z);vehicle.add(locker)}});vehicle.add(fireCab,fireGlass,fireTank,cannonBase,cannon,fireBeacon,fireHeadlights);const emergencyWheelGeo=new THREE.CylinderGeometry(.22,.22,.14,18),emergencyWheelMat=new THREE.MeshStandardMaterial({color:0x111519,roughness:.9}),emergencyWheels:THREE.Mesh[]=[];[[-.62,-.76],[.62,-.76],[-.62,.76],[.62,.76]].forEach(([x,z])=>{const wheel=new THREE.Mesh(emergencyWheelGeo,emergencyWheelMat);wheel.rotation.z=Math.PI/2;wheel.position.set(x,-.32,z);emergencyWheels.push(wheel);vehicle.add(wheel)});const fireAsset:SceneAsset={id:"firetruck",label:"泡沫消防车 01",category:"动态应急车辆 · OSM 真实道路",details:"真实道路网络正在加载，消防车将在道路中心线上执行任务。",meta:"OSM 路网 A* · 实时轨迹和转向更新",action:"follow-vehicle",position:{x:-35,y:2,z:-30}};vehicle.castShadow=true;vehicle.userData={asset:fireAsset,modelQuality:"competition-realism-v2"};emergencyVehicle=vehicle;fireAssetData=fireAsset;scene.add(vehicle);interactive.push(vehicle);
    const ambulance=new THREE.Mesh(new RoundedBoxGeometry(1.2,.46,2.18,4,.12),new THREE.MeshPhysicalMaterial({color:0xe9f4f2,metalness:.25,roughness:.33,clearcoat:.68,clearcoatRoughness:.2,emissive:0x164b3f,emissiveIntensity:.16}));const ambulanceCab=new THREE.Mesh(new RoundedBoxGeometry(1.02,1.02,1.66,4,.13),new THREE.MeshPhysicalMaterial({color:0xf2f7f5,metalness:.18,roughness:.34,clearcoat:.72,clearcoatRoughness:.2}));ambulanceCab.position.set(0,.46,.08);const ambulanceGlass=new THREE.Mesh(new RoundedBoxGeometry(.76,.38,.035,3,.035),new THREE.MeshPhysicalMaterial({color:0x75a9b7,metalness:.7,roughness:.1,clearcoat:1,transparent:true,opacity:.9}));ambulanceGlass.position.set(0,.6,-.77);const stripe=new THREE.Mesh(new RoundedBoxGeometry(1.23,.13,1.58,2,.025),new THREE.MeshBasicMaterial({color:0x2fb797}));stripe.position.set(0,.43,.1);const medicalBeacon=new THREE.Mesh(new RoundedBoxGeometry(.62,.12,.2,2,.035),new THREE.MeshBasicMaterial({color:0x33d8ff}));medicalBeacon.position.set(0,1.03,-.3);const medicalHeadlights=new THREE.Mesh(new RoundedBoxGeometry(.62,.11,.035,2,.025),fireLightMat);medicalHeadlights.position.set(0,.06,-1.11);const roofVent=new THREE.Mesh(new RoundedBoxGeometry(.48,.12,.42,2,.035),new THREE.MeshStandardMaterial({color:0xd7e0df,metalness:.42,roughness:.42}));roofVent.position.set(0,1.03,.43);const rearStep=new THREE.Mesh(new RoundedBoxGeometry(.86,.08,.18,2,.025),lockerMat);rearStep.position.set(0,-.08,1.15);const redCrossMat=new THREE.MeshBasicMaterial({color:0xe83b35});[-.52,.52].forEach(x=>{const crossV=new THREE.Mesh(new THREE.BoxGeometry(.025,.42,.13),redCrossMat),crossH=new THREE.Mesh(new THREE.BoxGeometry(.025,.13,.42),redCrossMat);crossV.position.set(x,.55,.25);crossH.position.set(x,.55,.25);ambulance.add(crossV,crossH)});ambulance.add(ambulanceCab,ambulanceGlass,stripe,medicalBeacon,medicalHeadlights,roofVent,rearStep);const ambulanceWheels:THREE.Mesh[]=[];[[-.6,-.68],[.6,-.68],[-.6,.68],[.6,.68]].forEach(([x,z])=>{const wheel=new THREE.Mesh(emergencyWheelGeo,emergencyWheelMat);wheel.rotation.z=Math.PI/2;wheel.position.set(x,-.31,z);ambulanceWheels.push(wheel);ambulance.add(wheel)});const ambulanceAsset:SceneAsset={id:"ambulance",label:"救护车 03",category:"动态医疗车辆 · 可跟随",details:"当前位置：体育中心 · 载员 4 人，正在前往临时分诊点。",meta:"车辆状态：待命转运 · 支持近距离跟随观察",action:"follow-vehicle",position:{x:-28,y:2,z:23}};ambulance.position.set(-28,.7,23);ambulance.rotation.y=-.72;ambulance.userData={asset:ambulanceAsset,modelQuality:"competition-realism-v2"};ambulance.castShadow=true;scene.add(ambulance);interactive.push(ambulance);
    const chemicalTruck=new THREE.Group(),chemicalChassis=new THREE.Mesh(new RoundedBoxGeometry(1.25,.38,2.55,3,.1),new THREE.MeshStandardMaterial({color:0x293438,metalness:.56,roughness:.36})),chemicalCab=new THREE.Mesh(new RoundedBoxGeometry(1.08,.92,.85,4,.12),new THREE.MeshPhysicalMaterial({color:0xd6a92f,metalness:.42,roughness:.28,clearcoat:.72,clearcoatRoughness:.18})),chemicalTank=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,1.45,28),new THREE.MeshPhysicalMaterial({color:0xb9c59c,metalness:.4,roughness:.36,clearcoat:.42,clearcoatRoughness:.28,emissive:0x3e4b20,emissiveIntensity:.1}));chemicalCab.position.set(0,.45,-.78);chemicalTank.rotation.x=Math.PI/2;chemicalTank.position.set(0,.54,.44);chemicalChassis.position.y=-.02;const chemicalGlass=new THREE.Mesh(new RoundedBoxGeometry(.76,.34,.04,3,.035),new THREE.MeshPhysicalMaterial({color:0x739eaa,metalness:.74,roughness:.1,clearcoat:1,transparent:true,opacity:.9}));chemicalGlass.position.set(0,.58,-1.22);const hazardStripe=new THREE.Mesh(new RoundedBoxGeometry(1.28,.13,1.48,2,.025),new THREE.MeshBasicMaterial({color:0xe6c137}));hazardStripe.position.set(0,.39,.45);const chemicalBeacon=new THREE.Mesh(new RoundedBoxGeometry(.62,.11,.18,2,.03),new THREE.MeshBasicMaterial({color:0xffa523}));chemicalBeacon.position.set(0,.98,-.75);const chemicalWheels:THREE.Mesh[]=[];[[-.62,-.78],[.62,-.78],[-.62,.78],[.62,.78]].forEach(([x,z])=>{const wheel=new THREE.Mesh(emergencyWheelGeo,emergencyWheelMat);wheel.rotation.z=Math.PI/2;wheel.position.set(x,-.29,z);chemicalWheels.push(wheel);chemicalTruck.add(wheel)});const chemicalAsset:SceneAsset={id:"chemical-truck",label:"化学废料运输车 京A·WH2576",category:"事故车辆 · 真实道路动态",details:"装载含氯化学废料 12.6 吨，正在沿北京真实道路执行转运任务。",meta:"车速 32 km/h · 罐体压力 0.42 MPa · 遥测在线",action:"follow-vehicle",position:{x:-29,y:1.5,z:-8}};chemicalChassis.userData={asset:chemicalAsset,modelQuality:"competition-realism-v2"};chemicalTruck.add(chemicalChassis,chemicalCab,chemicalTank,chemicalGlass,hazardStripe,chemicalBeacon);chemicalTruck.castShadow=true;scene.add(chemicalTruck);interactive.push(chemicalChassis);
    const leakMaterial=new THREE.MeshBasicMaterial({color:0xd6d85d,transparent:true,opacity:.26,depthWrite:false}),leakParticles:THREE.Mesh[]=[];const leakGroup=new THREE.Group();for(let i=0;i<18;i++){const particle=new THREE.Mesh(new THREE.SphereGeometry(.16+(i%4)*.055,10,8),leakMaterial);particle.userData.seed=i;leakParticles.push(particle);leakGroup.add(particle)}const hazardHalo=new THREE.Mesh(new THREE.RingGeometry(.72,1.02,32),new THREE.MeshBasicMaterial({color:0xffcf43,transparent:true,opacity:.72,side:THREE.DoubleSide,depthWrite:false}));hazardHalo.rotation.x=-Math.PI/2;hazardHalo.position.set(0,.04,.7);leakGroup.add(hazardHalo);leakGroup.visible=false;chemicalTruck.add(leakGroup);
    const policeCar=new THREE.Group(),policeBody=new THREE.Mesh(new RoundedBoxGeometry(.92,.38,1.9,4,.11),new THREE.MeshPhysicalMaterial({color:0xe8eff0,metalness:.52,roughness:.26,clearcoat:.85,clearcoatRoughness:.16})),policeCab=new THREE.Mesh(new RoundedBoxGeometry(.78,.48,.78,4,.09),new THREE.MeshPhysicalMaterial({color:0x47728a,metalness:.7,roughness:.11,clearcoat:1,transparent:true,opacity:.91}));policeBody.position.y=.05;policeCab.position.set(0,.43,.02);const policeBluePanel=new THREE.Mesh(new RoundedBoxGeometry(.94,.17,1.25,2,.025),new THREE.MeshBasicMaterial({color:0x2459a8}));policeBluePanel.position.set(0,.18,.08);const policeRedBeacon=new THREE.Mesh(new RoundedBoxGeometry(.28,.11,.18,2,.03),new THREE.MeshBasicMaterial({color:0xff413a})),policeBlueBeacon=new THREE.Mesh(new RoundedBoxGeometry(.28,.11,.18,2,.03),new THREE.MeshBasicMaterial({color:0x278dff}));policeRedBeacon.position.set(-.17,.72,-.08);policeBlueBeacon.position.set(.17,.72,-.08);const policeWheels:THREE.Mesh[]=[];[[-.48,-.58],[.48,-.58],[-.48,.58],[.48,.58]].forEach(([x,z])=>{const wheel=new THREE.Mesh(emergencyWheelGeo,emergencyWheelMat);wheel.scale.set(.82,.82,.82);wheel.rotation.z=Math.PI/2;wheel.position.set(x,-.2,z);policeWheels.push(wheel);policeCar.add(wheel)});const policeAsset:SceneAsset={id:"police-car",label:"公安疏散警车 07",category:"交通管制车辆 · 可跟随",details:"执行事故点周边道路封控、应急车道清空和下风向人员疏散。",meta:"警力 4 人 · 3 个路口联动 · 疏散通道已规划",action:"follow-vehicle",position:{x:31,y:1.4,z:-28}};policeBody.userData={asset:policeAsset,modelQuality:"competition-realism-v2"};policeCar.add(policeBody,policeCab,policeBluePanel,policeRedBeacon,policeBlueBeacon);scene.add(policeCar);interactive.push(policeBody);
    const realismChrome=new THREE.MeshStandardMaterial({color:0xb6c4c8,metalness:.88,roughness:.16}),realismDark=new THREE.MeshStandardMaterial({color:0x172127,metalness:.5,roughness:.36}),realismGlass=new THREE.MeshPhysicalMaterial({color:0x74a8b5,metalness:.72,roughness:.08,clearcoat:1,transparent:true,opacity:.86}),realismAmber=new THREE.MeshBasicMaterial({color:0xffb32d}),realismRed=new THREE.MeshBasicMaterial({color:0xff3f34});
    const addWheelHubs=(parent:THREE.Object3D,wheels:THREE.Mesh[])=>wheels.forEach(wheel=>{const rim=new THREE.Mesh(new THREE.CylinderGeometry(.085,.085,.15,14),realismChrome);rim.rotation.z=Math.PI/2;rim.position.copy(wheel.position);rim.scale.copy(wheel.scale);parent.add(rim)});
    const addContactShadow=(parent:THREE.Object3D,width:number,length:number,y:number)=>{const shadow=new THREE.Mesh(new THREE.CircleGeometry(1,32),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.scale.set(width,length,1);shadow.position.y=y;shadow.renderOrder=1;parent.add(shadow)};
    addWheelHubs(vehicle,emergencyWheels);addWheelHubs(ambulance,ambulanceWheels);addWheelHubs(chemicalTruck,chemicalWheels);addWheelHubs(policeCar,policeWheels);
    addContactShadow(vehicle,.82,1.5,-.535);addContactShadow(ambulance,.78,1.38,-.525);addContactShadow(chemicalTruck,.82,1.52,-.515);addContactShadow(policeCar,.65,1.12,-.39);
    const fireLadder=new THREE.Group();fireLadder.name="消防车伸缩云梯与器材组";[-.3,.3].forEach(x=>{const rail=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,1.55,8),realismChrome);rail.rotation.x=Math.PI/2;rail.position.set(x,1.02,.35);fireLadder.add(rail)});for(let rung=0;rung<7;rung++){const step=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,.62,7),realismChrome);step.rotation.z=Math.PI/2;step.position.set(0,1.02,-.26+rung*.2);fireLadder.add(step)}const hoseMaterial=new THREE.MeshStandardMaterial({color:0x19272c,metalness:.34,roughness:.55});[-.645,.645].forEach((x,index)=>{const reel=new THREE.Mesh(new THREE.TorusGeometry(.18,.032,8,20),hoseMaterial);reel.rotation.y=Math.PI/2;reel.position.set(x,.44,.42+index*.24);fireLadder.add(reel)});const fireGrille=new THREE.Mesh(new RoundedBoxGeometry(.68,.22,.035,2,.018),realismDark);fireGrille.position.set(0,.13,-1.225);const fireBumper=new THREE.Mesh(new RoundedBoxGeometry(1.12,.11,.12,2,.028),realismChrome);fireBumper.position.set(0,-.12,-1.22);vehicle.add(fireLadder,fireGrille,fireBumper);
    [-.515,.515].forEach(x=>{[-.35,.2,.65].forEach(z=>{const sideWindow=new THREE.Mesh(new RoundedBoxGeometry(.025,.26,.36,2,.025),realismGlass);sideWindow.position.set(x,.62,z);ambulance.add(sideWindow)})});const ambulanceRearDoorA=new THREE.Mesh(new RoundedBoxGeometry(.45,.72,.035,2,.02),new THREE.MeshStandardMaterial({color:0xe8f1ef,roughness:.36,metalness:.18})),ambulanceRearDoorB=ambulanceRearDoorA.clone();ambulanceRearDoorA.position.set(-.24,.48,1.12);ambulanceRearDoorB.position.set(.24,.48,1.12);const ambulanceBumper=new THREE.Mesh(new RoundedBoxGeometry(.96,.1,.13,2,.03),realismChrome);ambulanceBumper.position.set(0,-.08,-1.08);ambulance.add(ambulanceRearDoorA,ambulanceRearDoorB,ambulanceBumper);
    [-.04,.44,.91].forEach(z=>{const tankBand=new THREE.Mesh(new THREE.TorusGeometry(.49,.035,8,28),realismChrome);tankBand.position.set(0,.54,z);chemicalTruck.add(tankBand)});const tankCatwalk=new THREE.Mesh(new RoundedBoxGeometry(.34,.055,1.22,2,.02),realismDark);tankCatwalk.position.set(0,1.04,.43);const tankValve=new THREE.Mesh(new THREE.CylinderGeometry(.08,.11,.24,12),realismChrome);tankValve.rotation.x=Math.PI/2;tankValve.position.set(0,.54,1.19);const hazardPlacardLeft=new THREE.Mesh(new RoundedBoxGeometry(.025,.28,.28,2,.018),realismAmber),hazardPlacardRight=hazardPlacardLeft.clone();hazardPlacardLeft.position.set(-.64,.42,.42);hazardPlacardRight.position.set(.64,.42,.42);hazardPlacardLeft.rotation.x=Math.PI/4;hazardPlacardRight.rotation.x=Math.PI/4;chemicalTruck.add(tankCatwalk,tankValve,hazardPlacardLeft,hazardPlacardRight);
    const policeHood=new THREE.Mesh(new RoundedBoxGeometry(.82,.16,.54,3,.06),new THREE.MeshPhysicalMaterial({color:0xe8eff0,metalness:.48,roughness:.25,clearcoat:.86}));policeHood.position.set(0,.29,-.63);const policeTrunk=policeHood.clone();policeTrunk.scale.z=.68;policeTrunk.position.z=.7;[-.405,.405].forEach(x=>{const mirror=new THREE.Mesh(new RoundedBoxGeometry(.1,.07,.12,2,.025),realismDark);mirror.position.set(x,.46,-.15);policeCar.add(mirror);const sideWindow=new THREE.Mesh(new RoundedBoxGeometry(.025,.25,.42,2,.025),realismGlass);sideWindow.position.set(x,.48,.03);policeCar.add(sideWindow)});[-.22,.22].forEach(x=>{const headlight=new THREE.Mesh(new RoundedBoxGeometry(.16,.08,.035,2,.02),fireLightMat);headlight.position.set(x,.19,-.96);const tail=new THREE.Mesh(new RoundedBoxGeometry(.14,.075,.035,2,.02),realismRed);tail.position.set(x,.19,.96);policeCar.add(headlight,tail)});const policeBumper=new THREE.Mesh(new RoundedBoxGeometry(.84,.09,.1,2,.025),realismDark);policeBumper.position.set(0,-.08,-.97);policeCar.add(policeHood,policeTrunk,policeBumper);
    const roadblockGroup=new THREE.Group(),coneMaterial=new THREE.MeshStandardMaterial({color:0xff743d,emissive:0x6f1b08,emissiveIntensity:.25}),barrierMetalMaterial=new THREE.MeshStandardMaterial({color:0x566a70,metalness:.68,roughness:.32});[[-2.5,-1.1],[-1.6,-.75],[1.7,.75],[2.55,1.1]].forEach(([x,z])=>{const cone=new THREE.Mesh(new THREE.ConeGeometry(.16,.48,10),coneMaterial);cone.position.set(x,.24,z);roadblockGroup.add(cone)});const barrier=new THREE.Mesh(new THREE.BoxGeometry(3.3,.17,.12),new THREE.MeshBasicMaterial({color:0xffd34d}));barrier.position.set(0,.55,0);const barrierLegA=new THREE.Mesh(new THREE.BoxGeometry(.1,.8,.1),barrierMetalMaterial),barrierLegB=barrierLegA.clone();barrierLegA.position.set(-1.35,.38,0);barrierLegB.position.set(1.35,.38,0);roadblockGroup.add(barrier,barrierLegA,barrierLegB);roadblockGroup.position.set(-1.8,.16,-1.5);roadblockGroup.visible=false;scene.add(roadblockGroup);
    const evacuees:THREE.Group[]=[],personBodyGeo=new THREE.CylinderGeometry(.09,.12,.48,7),personHeadGeo=new THREE.SphereGeometry(.11,8,6),personBodyMaterials=[0x49b6e8,0xe5a74a,0x60c18a,0xb77bd1].map(color=>new THREE.MeshStandardMaterial({color,roughness:.75})),personHeadMaterial=new THREE.MeshStandardMaterial({color:0xd8b093,roughness:.8});for(let i=0;i<20;i++){const person=new THREE.Group(),body=new THREE.Mesh(personBodyGeo,personBodyMaterials[i%personBodyMaterials.length]),head=new THREE.Mesh(personHeadGeo,personHeadMaterial);body.position.y=.27;head.position.y=.63;person.add(body,head);person.userData.offsetX=(i%5)*.42-1,person.userData.offsetZ=Math.floor(i/5)*.38-.6;person.visible=false;scene.add(person);evacuees.push(person)}
    const foamGroup=new THREE.Group(),foamMaterial=new THREE.MeshBasicMaterial({color:0xd5fbff,transparent:true,opacity:.62,depthWrite:false});for(let i=0;i<16;i++){const foam=new THREE.Mesh(new THREE.SphereGeometry(.12+(i%3)*.05,9,7),foamMaterial);foam.userData.seed=i;foamGroup.add(foam)}foamGroup.position.set(-3,.2,-3);foamGroup.visible=false;scene.add(foamGroup);
    const triageGroup=new THREE.Group(),triageBase=new THREE.Mesh(new THREE.BoxGeometry(1.8,.08,1.35),new THREE.MeshStandardMaterial({color:0x4c8f78,roughness:.72})),triageCanopy=new THREE.Mesh(new THREE.ConeGeometry(1.12,.75,4),new THREE.MeshStandardMaterial({color:0xe6f2ed,roughness:.55})),triageCrossV=new THREE.Mesh(new THREE.BoxGeometry(.12,.5,.05),redCrossMat),triageCrossH=new THREE.Mesh(new THREE.BoxGeometry(.46,.12,.05),redCrossMat);triageCanopy.rotation.y=Math.PI/4;triageCanopy.position.y=.46;triageCrossV.position.set(0,.5,-.82);triageCrossH.position.set(0,.5,-.82);triageGroup.add(triageBase,triageCanopy,triageCrossV,triageCrossH);triageGroup.position.set(1.9,.1,1.6);triageGroup.visible=false;scene.add(triageGroup);
    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
    const selectionBox=new THREE.Box3Helper(new THREE.Box3(),0x62eeff);selectionBox.visible=false;(selectionBox.material as THREE.LineBasicMaterial).transparent=true;(selectionBox.material as THREE.LineBasicMaterial).opacity=.88;scene.add(selectionBox);
    const raycast=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(interactive,false)[0]};
    let lastHoverAt=0;const hover=(event:PointerEvent)=>{const now=performance.now();if(now-lastHoverAt<45)return;lastHoverAt=now;const hit=raycast(event),asset=hit?.object.userData.asset as SceneAsset|undefined;renderer.domElement.style.cursor=asset?"pointer":"grab";if(asset){hoverTip.textContent=asset.label;hoverTip.style.display="block";hoverTip.style.left=`${event.offsetX+14}px`;hoverTip.style.top=`${event.offsetY+14}px`}else hoverTip.style.display="none"};
    const leave=()=>{hoverTip.style.display="none";renderer.domElement.style.cursor="grab"};
    let selectedRoadMaterial:THREE.MeshBasicMaterial|null=null,selectedObject:THREE.Object3D|null=null,followTarget:THREE.Object3D|null=null;const pick=(event:PointerEvent)=>{const hit=raycast(event),asset=hit?.object.userData.asset as SceneAsset|undefined;if(selectedRoadMaterial){selectedRoadMaterial.opacity=.025;selectedRoadMaterial=null}selectedObject=hit?.object||null;if(asset){onSelectRef.current(asset);if(hit.object.userData.isRoad){selectedRoadMaterial=hit.object.material as THREE.MeshBasicMaterial;selectedRoadMaterial.opacity=.82;selectionBox.visible=false}else{selectionBox.box.setFromObject(hit.object);selectionBox.visible=true}}else selectionBox.visible=false};
    const doublePick=(event:MouseEvent)=>{const hit=raycast(event as PointerEvent),asset=hit?.object.userData.asset as SceneAsset|undefined;if(asset?.position){followTarget=null;camera.position.set(asset.position.x+8,asset.position.y+6,asset.position.z+8);controls.target.set(asset.position.x,asset.position.y,asset.position.z);controls.update()}};
    renderer.domElement.addEventListener("pointermove",hover);renderer.domElement.addEventListener("pointerleave",leave);renderer.domElement.addEventListener("pointerup",pick);renderer.domElement.addEventListener("dblclick",doublePick);
    const cameraAction=(event:Event)=>{const detail=(event as CustomEvent).detail,action=typeof detail==="string"?detail:detail?.action;if(action==="follow"){followTarget=detail.assetId?interactive.find(object=>(object.userData.asset as SceneAsset|undefined)?.id===detail.assetId)||null:null}if(action==="toggle-building-lights"&&detail.assetId){const target=interactive.find(object=>(object.userData.asset as SceneAsset|undefined)?.id===detail.assetId&&object.userData.isBuilding) as THREE.Mesh|undefined;if(target){const materials=Array.isArray(target.material)?target.material:[target.material],wall=materials[0] as THREE.MeshStandardMaterial;if(manualLitMaterials.has(wall))manualLitMaterials.delete(wall);else manualLitMaterials.add(wall);applyMode(nightRef.current)}}if(action==="zoomIn")camera.position.multiplyScalar(.85);if(action==="zoomOut")camera.position.multiplyScalar(1.15);if(action==="incident"){followTarget=null;camera.position.set(25,24,28);controls.target.set(-3,2,-3)}if(action==="focus"&&detail.position){followTarget=null;const p=detail.position;camera.position.set(p.x+13,p.y+11,p.z+13);controls.target.set(p.x,p.y,p.z)}if(action==="reset"){followTarget=null;camera.position.set(92,100,108);controls.target.set(0,6,0)}controls.update()};window.addEventListener("city-camera",cameraAction);
    const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();
    const pathMetricCache=new WeakMap<Array<{x:number;z:number}>,{lengths:number[];total:number}>();
    const sampleRoadPath=(path:Array<{x:number;z:number}>,progress:number)=>{if(path.length<2){const only=path[0]||{x:-39.704,z:-31.899};return new THREE.Vector3(only.x,.65,only.z)}let metric=pathMetricCache.get(path);if(!metric){const lengths:number[]=[];let total=0;for(let i=1;i<path.length;i++){const length=Math.hypot(path[i].x-path[i-1].x,path[i].z-path[i-1].z);lengths.push(length);total+=length}metric={lengths,total};pathMetricCache.set(path,metric)}let target=Math.max(0,Math.min(.999999,progress))*metric.total;for(let i=0;i<metric.lengths.length;i++){if(target<=metric.lengths[i]){const ratio=metric.lengths[i]?target/metric.lengths[i]:0;return new THREE.Vector3(THREE.MathUtils.lerp(path[i].x,path[i+1].x,ratio),.65,THREE.MathUtils.lerp(path[i].z,path[i+1].z,ratio))}target-=metric.lengths[i]}const last=path[path.length-1];return new THREE.Vector3(last.x,.65,last.z)};
    const clamp01=(value:number)=>Math.max(0,Math.min(1,value)),placeOnRoad=(object:THREE.Object3D,path:Array<{x:number;z:number}>,progress:number,asset?:SceneAsset)=>{const safeProgress=clamp01(progress),position=sampleRoadPath(path,safeProgress),aheadProgress=Math.min(.998,safeProgress+.006),ahead=sampleRoadPath(path,aheadProgress);object.position.copy(position);if(aheadProgress>safeProgress){object.lookAt(ahead);object.rotation.y+=Math.PI;object.rotation.x=0;object.rotation.z=0}if(asset?.position){asset.position.x=position.x;asset.position.y=1.5;asset.position.z=position.z}return position};
    const chemicalFallback=[{x:-64.181,z:-2.804},{x:-34,z:-5},{x:-3,z:-3}],ambulanceFallback=[{x:-32.836,z:28.859},{x:-20,z:16},{x:-3,z:-3}],policeFallback=[{x:19.766,z:-19.999},{x:11,z:-13},{x:-3,z:-3}],fireFallback=[{x:-35,z:-30},{x:-20,z:-18},{x:-3,z:-3}];
    const clock=new THREE.Clock(),followPosition=new THREE.Vector3(),followQuaternion=new THREE.Quaternion(),followOffset=new THREE.Vector3(),cameraGoal=new THREE.Vector3(),controlGoal=new THREE.Vector3(),tourGoal=new THREE.Vector3(0,5,0);let frame=0,shadowTick=0,lastTrafficT=0;
    const animate=()=>{
      frame=requestAnimationFrame(animate);if(suspendedRef.current||document.hidden){if(shadowTick++%18===0){controls.update();renderer.render(scene,camera)}return}const t=clock.getElapsedTime(),trafficDelta=Math.min(.05,Math.max(0,t-lastTrafficT)),phase=scenarioPhaseRef.current,playhead=scenarioTimeRef.current,scenarioActive=phase>0,recoveryScale=phase===9?.36:1;lastTrafficT=t;
      incidentLandmark.visible=scenarioActive&&phase>=2;
      if(tourRef.current){followTarget=null;const a=t*.055+.7,radius=142;camera.position.set(Math.cos(a)*radius,78+Math.sin(t*.11)*9,Math.sin(a)*radius);controls.target.lerp(tourGoal,.08)}
      riskMeshes.forEach((mesh,index)=>{const pulse=1+Math.sin(t*1.6+index)*.035,base=riskBaseRef.current[index];mesh.scale.set(base[0]*pulse*recoveryScale,base[1]*pulse*recoveryScale,1);(mesh.material as THREE.MeshBasicMaterial).opacity=[.18,.23,.3][index]*(.8+Math.sin(t*1.8+index)*.2)*(phase===9?.35:1)});
      const effectiveTraffic=phase>=6?Math.min(trafficDensityRef.current,18):trafficDensityRef.current;
      movingTraffic.forEach((car,index)=>{car.mesh.visible=index<effectiveTraffic;if(!car.mesh.visible)return;const speedFactor=phase>=2&&phase<6?.62:1;car.travel=(car.travel+trafficDelta*car.speed*speedFactor)%2;const forward=car.travel<1,u=forward?car.travel:2-car.travel,aheadU=Math.max(0,Math.min(1,u+(forward?.004:-.004)));car.curve.getPointAt(u,car.position);car.curve.getPointAt(aheadU,car.ahead);const position=car.position,ahead=car.ahead;car.mesh.position.copy(position);if(Math.abs(aheadU-u)>.0001){car.mesh.lookAt(ahead);car.mesh.rotation.y+=Math.PI;car.mesh.rotation.x=0;car.mesh.rotation.z=0}car.wheels.forEach(wheel=>wheel.rotation.y-=trafficDelta*(12+index%4)*speedFactor);car.indicator.opacity=Math.sin(t*4+index*.7)>.55?1:.16;if(car.asset.position){car.asset.position.x=position.x;car.asset.position.y=1.1;car.asset.position.z=position.z}});
      const chemicalPath=chemicalRoutePath.length>1?chemicalRoutePath:chemicalFallback,ambulancePath=ambulanceRoutePath.length>1?ambulanceRoutePath:ambulanceFallback,policePath=policeRoutePath.length>1?policeRoutePath:policeFallback,activeFirePath=realRouteRef.current.length>1?realRouteRef.current:fireFallback;
      const chemicalProgress=scenarioActive?clamp01(playhead/7):0;placeOnRoad(chemicalTruck,chemicalPath,chemicalProgress,chemicalAsset);if(scenarioActive&&playhead>=7&&playhead<8.2)chemicalTruck.position.x+=Math.sin(playhead*34)*.045;chemicalWheels.forEach(wheel=>wheel.rotation.y=-playhead*8*chemicalProgress);chemicalBeacon.visible=scenarioActive&&phase>=2&&Math.sin(t*11)>.05;
      leakGroup.visible=scenarioActive&&phase>=2;leakMaterial.opacity=phase===9?.08:.28;if(leakGroup.visible){const leakAge=Math.max(0,playhead-7);leakParticles.forEach((particle,index)=>{const cycle=(leakAge*.24+index*.113)%1,angle=index*2.17;particle.position.set(Math.cos(angle)*(.22+cycle*1.5),.48+cycle*2.1,.68+Math.sin(angle)*(.18+cycle*1.7));particle.scale.setScalar(.65+cycle*1.4)});const haloPulse=1+Math.sin(t*5)*.13;hazardHalo.scale.setScalar(haloPulse)}
      chemicalRouteLayer.visible=scenarioActive&&phase===1;(chemicalRouteLayer.material as THREE.MeshBasicMaterial).opacity=.34;
      routeA.visible=scenarioActive?phase>=4:runningRef.current;ambulanceRouteLayer.visible=scenarioActive&&phase>=4;policeRouteLayer.visible=scenarioActive&&phase>=4;
      const routeColor=phase===9?0x54e7a8:0x28d9ef;(routeA.material as THREE.MeshBasicMaterial).color.setHex(routeColor);(ambulanceRouteLayer.material as THREE.MeshBasicMaterial).color.setHex(phase===9?0x54e7a8:0x4ce3b1);(policeRouteLayer.material as THREE.MeshBasicMaterial).color.setHex(phase===9?0x54e7a8:0x4a91ff);
      if(scenarioActive){const fireProgress=clamp01((playhead-27)/22);placeOnRoad(vehicle,activeFirePath,fireProgress*.985,fireAsset);emergencyWheels.forEach(wheel=>wheel.rotation.y=-fireProgress*48);const medicalProgress=clamp01((playhead-27)/32);placeOnRoad(ambulance,ambulancePath,medicalProgress*.92,ambulanceAsset);ambulanceWheels.forEach(wheel=>wheel.rotation.y=-medicalProgress*52);const policeProgress=clamp01((playhead-27)/13);placeOnRoad(policeCar,policePath,policeProgress*.84,policeAsset);policeWheels.forEach(wheel=>wheel.rotation.y=-policeProgress*42)}else{placeOnRoad(vehicle,activeFirePath,0,fireAsset);placeOnRoad(ambulance,ambulancePath,0,ambulanceAsset);placeOnRoad(policeCar,policePath,0,policeAsset)}
      fireBeacon.visible=(scenarioActive?phase>=4:runningRef.current)&&Math.sin(t*9)>-.2;medicalBeacon.visible=scenarioActive&&phase>=4&&Math.sin(t*8+1)<.25;policeRedBeacon.visible=scenarioActive&&phase>=4&&Math.sin(t*12)>.05;policeBlueBeacon.visible=scenarioActive&&phase>=4&&Math.sin(t*12)<=.05;
      roadblockGroup.visible=scenarioActive&&phase>=6;evacuees.forEach((person,index)=>{person.visible=scenarioActive&&phase>=6;if(!person.visible)return;const progress=clamp01((playhead-40)/9),offsetX=person.userData.offsetX as number,offsetZ=person.userData.offsetZ as number;person.position.set(35+offsetX+progress*16,.02,-23+offsetZ-progress*12+Math.sin(playhead*5+index)*.08);person.rotation.y=-.65;person.children[0].rotation.z=Math.sin(playhead*8+index)*.12});
      foamGroup.visible=scenarioActive&&phase>=7;foamGroup.children.forEach((foam,index)=>{const cycle=((playhead-49)*.5+index*.09)%1,angle=index*.84;foam.position.set(Math.cos(angle)*(cycle*2.2),.18+cycle*.8,Math.sin(angle)*(cycle*2.2));foam.scale.setScalar(.7+cycle*1.25)});triageGroup.visible=scenarioActive&&phase>=8;
      if(scenarioActive){chemicalAsset.details=phase===1?"装载含氯化学废料 12.6 吨，沿 OSM 真实道路正常行驶。":"动力系统故障，尾阀受冲击松动并发生含氯废料泄漏。";chemicalAsset.meta=phase===1?"车速 32 km/h · 罐体压力 0.42 MPa · 遥测正常":`车辆已停车 · AI 告警生效 · 联合响应阶段 ${String(phase).padStart(2,"0")}/09`;policeAsset.meta=phase>=6?"已到场 · 3 个路口封控 · 186 人向侧上风向疏散":"警力 4 人 · 正沿真实道路赶赴现场";ambulanceAsset.meta=phase>=8?"已到场 · 2 名轻度吸入人员完成检伤":"医疗组 4 人 · 绿色通道已开启"}
      if(selectedObject&&selectionBox.visible)selectionBox.box.setFromObject(selectedObject);if(followTarget&&!tourRef.current){followTarget.getWorldPosition(followPosition);followTarget.getWorldQuaternion(followQuaternion);followOffset.set(3.3,2.25,4.8).applyQuaternion(followQuaternion);cameraGoal.copy(followPosition).add(followOffset);controlGoal.copy(followPosition);controlGoal.y+=.38;camera.position.lerp(cameraGoal,.12);controls.target.lerp(controlGoal,.18)}controls.update();if(shadowTick++%3===0)renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera)
    };animate();
    return()=>{
      applyModeRef.current=()=>{};realRoutePlannerRef.current=()=>{};abortBuildings.abort();cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener("city-camera",cameraAction);renderer.domElement.removeEventListener("pointermove",hover);renderer.domElement.removeEventListener("pointerleave",leave);renderer.domElement.removeEventListener("pointerup",pick);renderer.domElement.removeEventListener("dblclick",doublePick);controls.dispose();
      const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();
      scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.LineSegments||object instanceof THREE.Sprite||object instanceof THREE.Points){if("geometry" in object&&object.geometry)geometries.add(object.geometry as THREE.BufferGeometry);const material="material" in object?object.material:null;(Array.isArray(material)?material:material?[material]:[]).forEach(entry=>{materials.add(entry as THREE.Material);Object.values(entry as THREE.Material).forEach(value=>{if(value instanceof THREE.Texture)textures.add(value)})})}});
      geometries.forEach(geometry=>geometry.dispose());materials.forEach(material=>material.dispose());textures.forEach(texture=>texture.dispose());renderer.renderLists.dispose();renderer.dispose();renderer.forceContextLoss();el.innerHTML="";
    };
  }, []);
  return <div className={`real-3d-scene ${nightMode?"night":"day"}`} ref={host} onClick={e=>e.stopPropagation()}><div className="scene-badge"><i />北京核心区真实地图 · {scenarioPhase>0?`全流程演示 ${String(scenarioPhase).padStart(2,"0")}/09`:"精修建筑"} · {nightMode?"夜间态势":"白天态势"}</div><div className="scene-help">实时车流 {trafficDensity} 辆 · 单击查看详情 · 双击快速聚焦 · {autoTour?"自动巡航中":"可自由旋转"}</div></div>;
}
